### PR TITLE
Backport: Switch lifecycle to use the RCLCPP macros

### PR DESCRIPTION
**Pull request by tonynajjar**
Backport of https://github.com/ros2/rclcpp/pull/2233. Tested on Humble, works as expected.

### CODE REVIEW

**Comment by clalancette** [comment]
Yeah, we need to do a release of `rcl` into Humble to fix that.  @audrow what are your plans for a full Humble patch release?

**Comment by clalancette** [comment]
Regardless, that doesn't block this PR; we can build everything from source and get confidence that way.  That said, I'm not going to do any of that until #2233 is merged into Rolling.

**Comment by tonynajjar** [comment]
> Regardless, that doesn't block this PR; we can build everything from source and get confidence that way. That said, I'm not going to do any of that until #2233 is merged into Rolling.

Makes sense. I quickly checked that for Iron there are no conflicts, so it should be a smooth backport with mergify

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19208/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13768/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19949/)

**Review by fujitatomoya — APPROVED** [review]

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/new-packages-and-patch-release-for-humble-hawksbill-2023-07-24/32523/6

**Pull request merged**
