### PR TITLE
remove excess sleep

### PR DESCRIPTION
**Pull request by tfoote**
CI: 
- http://ci.ros2.org/job/ci_linux/760 (expected)
- http://ci.ros2.org/job/ci_osx/640/
- http://ci.ros2.org/job/ci_windows/825/

 identified in #169

### CODE REVIEW

**Comment by esteve** [comment]
+1

**Comment by tfoote** [comment]
@gerkey There are some failures of the multithreaded tests on osx, which this is changing. Are those addressed in the other threads?

**Comment by gerkey** [comment]
@tfoote From your OSX build (http://ci.ros2.org/job/ci_osx/640/consoleFull#console-section-170), of these failures in `test_rclcpp`:

~~~
19:30:29 	  6 - gtest_subscription__rmw_connext_cpp (Timeout)
19:30:29 	 11 - gtest_multithreaded__rmw_connext_cpp (Failed)
19:30:29 	 20 - gtest_subscription__rmw_connext_dynamic_cpp (Timeout)
19:30:29 	 25 - gtest_multithreaded__rmw_connext_dynamic_cpp (Failed)
19:30:29 	 39 - gtest_multithreaded__rmw_opensplice_cpp (Failed)
~~~

I believe that the two Timeouts are fixed by ros2/system_tests#90.

The three Failed tests, however, appear to be crashes. E.g., this one is death by `SIGABRT` (6):

~~~
19:27:41 11: [ RUN      ] test_multithreaded__.multi_consumer_single_producer
19:27:42 11: gtest_multithreaded__rmw_connext_cpp(74758,0x103287000) malloc: *** error for object 0x7fb420eb7840: double free
19:27:42 11: *** set a breakpoint in malloc_error_break to debug
19:27:42 11: RTI Data Distribution Service Evaluation License issued to OSRF (OSRF01) dthomas@osrfoundation.org For non-production use only.
19:27:42 11: Expires on 08-jun-2016 See www.rti.com for more information.
19:27:42 11: callback()    1 with message data 1
19:27:42 11: callback()    2 with message data 1
19:27:42 11: callback()    3 with message data 1
19:27:42 11: callback()    4 with message data 1
19:27:42 11: callback()    1 with message data 1
19:27:42 11: -- run_test.py: return code -6
~~~

There's another one like that. And this one is a death by SIGSEGV (11):

~~~
19:30:17 39: [ RUN      ] test_multithreaded__.multi_consumer_single_producer
19:30:19 39: -- run_test.py: return code -11
~~~

**Comment by gerkey** [comment]
Hmm, I really hope that that sleep isn't what was preventing those programs from crashing previously...

**Comment by jacquelinekay** [comment]
I think I'm suffering PTSD from seeing those test failures.

**Comment by jacquelinekay** [comment]
Actually, now that I think about it, those segfaults could be explained by concurrent access to `thread_number_by_thread_id` (line 70: https://github.com/ros2/rclcpp/blob/master/rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp#L70)

I'll fire up GDB and take a look. If that is the case, we can protect the data structure with a mutex, or get rid of it entirely since it isn't currently being used.

**Comment by jacquelinekay** [comment]
huh. I don't see the crashes when I test this locally, only opensplice or connext. I do see intermittent failures but those should be fixed by @gerkey's upcoming pull request.

**Comment by gerkey** [comment]
It took some effort on my laptop (finding that my version of clang is not new enough to compile everything, learning how to "codesign" gdb so that is has permission to run, learning that gdb can no longer parse core files generated on OSX, learning how to use lldb, including the apparently undocumented feature of loading a core file with `-c`), but I was able to reproduce the segmentation fault, at least in the opensplice case. Here's the backtrace from `./build/test_rclcpp/gtest_multithreaded__rmw_opensplice_cpp`:

~~~
* thread #1: tid = 0x0000, 0x0000000108c61188 librclcpp.dylib`std::__1::__hash_table<std::__1::__hash_value_type<std::__1::__thread_id, unsigned long>, std::__1::__unordered_map_hasher<std::__1::__thread_id, std::__1::__hash_value_type<std::__1::__thread_id, unsigned long>, std::__1::hash<std::__1::__thread_id>, true>, std::__1::__unordered_map_equal<std::__1::__thread_id, std::__1::__hash_value_type<std::__1::__thread_id, unsigned long>, std::__1::equal_to<std::__1::__thread_id>, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::__thread_id, unsigned long> > >::__node_insert_unique(std::__1::__hash_node<std::__1::__hash_value_type<std::__1::__thread_id, unsigned long>, void*>*) + 2744, stop reason = signal SIGSTOP
  * frame #0: 0x0000000108c61188 librclcpp.dylib`std::__1::__hash_table<std::__1::__hash_value_type<std::__1::__thread_id, unsigned long>, std::__1::__unordered_map_hasher<std::__1::__thread_id, std::__1::__hash_value_type<std::__1::__thread_id, unsigned long>, std::__1::hash<std::__1::__thread_id>, true>, std::__1::__unordered_map_equal<std::__1::__thread_id, std::__1::__hash_value_type<std::__1::__thread_id, unsigned long>, std::__1::equal_to<std::__1::__thread_id>, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::__thread_id, unsigned long> > >::__node_insert_unique(std::__1::__hash_node<std::__1::__hash_value_type<std::__1::__thread_id, unsigned long>, void*>*) + 2744
    frame #1: 0x0000000108c5f94d librclcpp.dylib`std::__1::unordered_map<std::__1::__thread_id, unsigned long, std::__1::hash<std::__1::__thread_id>, std::__1::equal_to<std::__1::__thread_id>, std::__1::allocator<std::__1::pair<std::__1::__thread_id const, unsigned long> > >::operator[](std::__1::__thread_id&&) + 701
    frame #2: 0x0000000108c5eee9 librclcpp.dylib`rclcpp::executors::multi_threaded_executor::MultiThreadedExecutor::run(unsigned long) + 201
    frame #3: 0x0000000108c5ebea librclcpp.dylib`rclcpp::executors::multi_threaded_executor::MultiThreadedExecutor::spin() + 2026
    frame #4: 0x0000000108701146 gtest_multithreaded__rmw_opensplice_cpp`multi_consumer_pub_sub_test(bool) + 6342
    frame #5: 0x00000001086ff875 gtest_multithreaded__rmw_opensplice_cpp`test_multithreaded___multi_consumer_single_producer_Test::TestBody() + 21
    frame #6: 0x00000001087c576c libgtest.0.dylib`void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 80
    frame #7: 0x00000001087b6294 libgtest.0.dylib`testing::Test::Run() + 122
    frame #8: 0x00000001087b6b4e libgtest.0.dylib`testing::TestInfo::Run() + 168
    frame #9: 0x00000001087b7052 libgtest.0.dylib`testing::TestCase::Run() + 184
    frame #10: 0x00000001087bbfd8 libgtest.0.dylib`testing::internal::UnitTestImpl::RunAllTests() + 624
    frame #11: 0x00000001087c5e61 libgtest.0.dylib`bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) + 77
    frame #12: 0x00000001087bbd28 libgtest.0.dylib`testing::UnitTest::Run() + 100
    frame #13: 0x000000010871c051 gtest_multithreaded__rmw_opensplice_cpp`RUN_ALL_TESTS() + 17
    frame #14: 0x0000000108706ea4 gtest_multithreaded__rmw_opensplice_cpp`main + 52
    frame #15: 0x00007fff8fc405c9 libdyld.dylib`start + 1
~~~

There's not a ton of detail there (it's not a debug build), but the fact that we depart from `MultiThreadedExecutor::run()` into an operation on an `unordered_map` and then die supports @jacquelinekay's hypothesis that the underlying cause is concurrent access to `thread_number_by_thread_id_`: https://github.com/ros2/rclcpp/blob/master/rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp#L70.

**Comment by gerkey** [comment]
After confirmed that it's not used anywhere in the code (and it was private, so there can't be any external users of it), I removed `thread_number_by_thread_id_` in a7a6111. I think that that's a better solution than protecting it with a mutex. We can reintroduce the structure, with protection, when we find a use for it.

**Comment by gerkey** [comment]
@wjwwood Looks like you added `thread_number_by_thread_id_` (0bbe9b2). You OK with deleting it for now and bringing it back later if we need it?

**Comment by gerkey** [comment]
Also, I can confirm from local testing that without this fix, I get either a deadlock or a segfault after several iterations and with this fix I can run the test back-to-back essentially forever.

**Comment by jacquelinekay** [comment]
+1 for removing the data structure until it's needed.

**Comment by wjwwood** [comment]
That's fine.

**Pull request merged**
