### PR TITLE
Attempt to fix cppcheck warning

### PR DESCRIPTION
**Pull request by sloretz**
connects to ros2/rmw_connext#348

ros2/build_cop#172

### CODE REVIEW

**Comment by sloretz** [comment]
CI (osx, testing ros2/rmw_connext#348, ros2/rmw_opensplice#261, and this)

[Build Status](https://ci.ros2.org/job/ci_osx/5183/)

**Comment by thomas-moulard** [comment]
@sloretz This PR is making the OS X and Windows build unstable - could you PTAL?

* https://ci.ros2.org/job/ci_windows/6165/testReport/junit/rclcpp/cppcheck/warning__nullPointer__src_rclcpp_clock_cpp_139_/
* https://ci.ros2.org/job/ci_osx/5194/testReport/junit/rclcpp/cppcheck/warning__nullPointer__src_rclcpp_clock_cpp_139_/

```
Possible null pointer dereference: handler
```

**Comment by sloretz** [comment]
> @sloretz This PR is making the OS X and Windows build unstable - could you PTAL?

@thomas-moulard It looks like the branch [`durationtype`](https://github.com/emersonknapp/rclcpp/commits/durationtype) needs to be rebased to include this PR. The warning started after upgrading cppcheck on the ci machines. This PR fixes it.

**Comment by thomas-moulard** [comment]
@sloretz you're right, of course. Thanks for explaining!

**Pull request merged**
