### PR TITLE
Add type_hash to cpp TopicEndpointInfo

### PR DESCRIPTION
**Pull request by emersonknapp**
Part of ros2/ros2#1159

From rep-2011 work, expose the new RMW endpoint info's type hash to the C++ endpoint struct.

### CODE REVIEW

**Comment by james-rms** [comment]
Gist: https://gist.githubusercontent.com/james-rms/fea80e655cfd2cff457bfdcf4608ad08/raw/3fa348b2ec65fc83f3763fa52cc69560fead4c11/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11785
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18434/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12980/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19118/)

**Comment by james-rms** [comment]
@ivanpauno @wjwwood @hidmic CI failure in github actions appears to be a flake, see passing CI runs in the comment above. It would help me to merge this, are you able to review?

**Comment by emersonknapp** [comment]
Not sure it's a flake so much as a temporary issue with some underlying package version - might be worth trying again to see if it's resolved with latest versions

**Comment by clalancette** [comment]
> Not sure it's a flake so much as a temporary issue with some underlying package version - might be worth trying again to see if it's resolved with latest versions - regardless it's warnings, not test failures, and clearly not in any of the source files in this package

Yeah, this is currently broken.  It will be resolved once we get the base set of packages released into Rolling.

**Review by methylDragon — APPROVED** [review]

**Review by clalancette — APPROVED** [review]
Looks good with green CI.

**Comment by clalancette** [comment]
> Looks good with green CI.

Actually, looks like CI was already green.  The yellow on Windows was from an unrelated change (and has since been fixed).  So I'm going to go ahead and merge this one.

**Pull request merged**
