### PR TITLE
Topic node guard condition in executor

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
to fix https://github.com/ros2/rclcpp/issues/2067

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos can you start CI?

**Comment by iuhilnehc-ynos** [comment]
CI: (build: `--packages-above-and-dependencies rclcpp` test: `--packages-above rclcpp`)

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17868/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12436/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18540/)

**Comment by alsora** [comment]
Looks good to me.
Was this bug caused by https://github.com/ros2/rclcpp/pull/1640 ?

**Review by alsora — APPROVED** [review]

**Comment by iuhilnehc-ynos** [comment]
@alsora 

> Was this bug caused by #1640 ?

Yes.

**Comment by alsora** [comment]
I'm merging this PR, since it has green CI and approvals.
We verified that it fixes some issues caused by missing notifications when adding/removing entities.

**Comment by fujitatomoya** [comment]
@alsora thanks for checking on this.

**Pull request merged**
