### PR TITLE
Remove unused test variable

### PR DESCRIPTION
**Pull request by dabonnie**
Related to https://github.com/ros2/rclcpp/pull/1072#issuecomment-618144438

Signed-off-by: Devin Bonnie <dbbonnie@amazon.com>

### CODE REVIEW

**Comment by dabonnie** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10418/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5924/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8496/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10310/)

**Comment by Karsten1987** [comment]
must be a typo in your config: `Package 'rrclcpp' specified with --packages-up-to was not found`

**Comment by dabonnie** [comment]
> must be a typo in your config: `Package 'rrclcpp' specified with --packages-up-to was not found`

I guess today's just not my day :-( trying again

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10419/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5925/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8497/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10312/)

**Comment by dabonnie** [comment]
> lgtm with green CI.

@Karsten1987 OSX warnings appear unrelated and test failures have occurred in the [last unstable build](https://ci.ros2.org/view/nightly/job/nightly_osx_release/1622/#showFailuresLink) (now red).

**Pull request merged**
