### PR TITLE
Revert "Revert "Store the subscriber, client, service and timer""

### PR DESCRIPTION
**Pull request by wjwwood**
Reverts ros2/rclcpp#448

@guillaumeautran and @deng02 FYI.

### CODE REVIEW

**Comment by guillaumeautran** [comment]
Hey @wjwwood, Yes, I see the problem. Sorry about that. Looking to clean that up now.

**Comment by guillaumeautran** [comment]
Ok, I found at least one of the root cause of the issue. it is explained here: http://floating.io/2017/07/lambda-shared_ptr-memory-leak/
fixing it...

**Comment by wjwwood** [comment]
No worries, that's why we have CI and nightlies 😄. It's not a hurry. I reverted it, so it's not affecting other people. I'll also have a look at it tomorrow if I can.

**Comment by guillaumeautran** [comment]
Ok, I've got a fix for these. @wjwwood could you please have a look and tell me if it is acceptable? 
Change is here: https://github.com/clearpathrobotics/rclcpp/commit/3bbb5dc6cf3aa98e2f02367363d502d02240c122

Note, that for simplicity purposes, the node_handle shared pointer (which does not work with lambda) is replaced by a weak pointer. This means that if the node handle is destructed before the service / subscriber handle, the rcl datastructure will leak (since the fini destructor needs a valid node pointer).

**Comment by guillaumeautran** [comment]
Ok, I've got a fix for these. @wjwwood could you please have a look and tell me if it is acceptable?

**Comment by guillaumeautran** [comment]
I'm also looking at UT this change but currently struggling to come up with a B/W test.

**Comment by wjwwood** [comment]
@guillaumeautran the patch looks pretty good to me, can you open a pull request against this pull requests's branch (`revert-448-revert-431-issue-349`)?

**Comment by wjwwood** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4104/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1194/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3398/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4208/)

**Comment by wjwwood** [comment]
I carefully went through the failures on each CI job and I believe them all to be unrelated this time. So I'll merge this. Thanks @guillaumeautran for helping fix it up!

**Pull request merged**
