### PR TITLE
Add support to musl

### PR DESCRIPTION
**Pull request by mauropasse**
Fixes issue:
https://github.com/ros2/rclcpp/issues/983

### CODE REVIEW

**Comment by mjcarroll** [comment]
Please signoff your commits so that DCO will pass.

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9257/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4941/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7564/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9176/)
* Windows-container [Build Status](http://ci.ros2.org/job/ci_windows-container/52/)

**Comment by mauropasse** [comment]
Hi @mjcarroll, the failing builds logs doesn't make any reference to errors due the changes of my commit:
```
16:02:24 ERROR: Step ‘[Deprecated] Scan for compiler warnings’ failed: no workspace for ci_linux-aarch64 #4941
16:02:24 ERROR: Step ‘Publish Cobertura Coverage Report’ failed: no workspace for ci_linux-aarch64 #4941
16:02:24 [xUnit] [INFO] - Starting to record.
16:02:24 [xUnit] [INFO] - Processing CTest-Version N/A (default)
16:02:24 ERROR: Build step failed with exception
16:02:24 java.lang.NullPointerException
16:02:24 Build step 'Publish xUnit test result report' marked build as failure
16:02:24 Finished: FAILURE
```

**Comment by ivanpauno** [comment]
@mjcarroll Copying a `ros2.repos` gist link in `CI_BRANCH_TO_TEST` doesn't work, `CI_ROS2_REPOS_URL` has to be used :wink:.

Another run:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9396/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5074/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7​68​8/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9​31​5/)

**Comment by mjcarroll** [comment]
Whoops, very good point :sweat_smile:

**Comment by mjcarroll** [comment]
@mauropasse This looks to have some linting issues, can you get those cleaned up?

**Comment by ivanpauno** [comment]
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7740/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9393/)

**Comment by mjcarroll** [comment]
Hey @mauropasse can you rebase this as it now has conflicts.

**Comment by mauropasse** [comment]
Since commit https://github.com/ros2/rclcpp/commit/f30329fbec79cb699f41a37cc27c0c475de3edc1 the fix is not needed anymore. Thanks! Closing PR

**Pull request closed without merging**
