### PR TITLE
open Node/Publisher API for allowing inheritance

### PR DESCRIPTION
**Pull request by Karsten1987**
change:
- `Node::create_publisher` function has a new template parameter for publisher type (`rclcpp::publisher::Publisher` by default)
- all `publish` functions are virtual for being able to inherit from

### CODE REVIEW

**Comment by wjwwood** [comment]
> Node gets extended with one template parameter for publisher type 

Isn't it more accurate to say that the `Node::create_publisher` method has a new template parameter? Node is still not templated as far as I can see.

**Comment by Karsten1987** [comment]
You're absolutely right. Corrected.

**Comment by Karsten1987** [comment]
updated

**Comment by Karsten1987** [comment]
build succesful http://ci.ros2.org/job/ci_linux/lastBuild/

**Comment by AravindaDP** [comment]
Probably we should open client API also for inheritance?

I'm specifically interested in marking async_send_request call as virtual.

Note: What's I have in mind is for the unit testing purposes. (Mocking) Correct me if it is wrong way to handle things.

**Comment by wjwwood** [comment]
@AravindaDP sorry it took so long to get back to you on this. If you'd like to see additional methods marked virtual, or a function refactored to take one of the arguments as a template, please just open a pr to that effect or open an issue for each case so we can evaluate them there.

**Comment by AravindaDP** [comment]
@wjwwood no worries. Actually I wasn't sure about the correct place I should open the discussion.
I'll open an issue so we can evaluate the best approach to achieve the requirement there.

**Pull request merged**
