### PR TITLE
[backport foxy] Reorganize test directory and split CMakeLists.txt (#1173)

### PR DESCRIPTION
**Pull request by brawner**
Signed-off-by: Stephen Brawner <brawner@gmail.com>

### CODE REVIEW

**Comment by brawner** [comment]
Testing `--packages-select rclcpp`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11784/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6865/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9623/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11727/)

**Comment by clalancette** [comment]
@brawner Friendly ping on this one.  I think the pytest problems should be sorted now, so this should be good for another try on CI (and a rebase, it looks like).

**Comment by brawner** [comment]
Fortunately the rebase was simple since it just moves file around (and the cmakelists.txt hasn't been changed)

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12015/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7040/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9791/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11949/)

**Comment by brawner** [comment]
macOS failure seems unrelated and I've seen that test fail many times before but it doesn't show up on nightlies. Trying again

* macOS [Build Status](https://ci.ros2.org/job/ci_osx/9797/)

**Comment by brawner** [comment]
I rebuilt the same job, but without the backport branch and it had the same issue. 
* macOS [Build Status](https://ci.ros2.org/job/ci_osx/9801/)

I believe this was a prexisting issue and unrelated to this PR.

**Pull request merged**
