### PR TITLE
Use new type support infrastructure

### PR DESCRIPTION
**Pull request by esteve**
This PR updates `rclcpp` to use the new type support infrastructure.

@dirk-thomas @tfoote @wjwwood please review.

### CODE REVIEW

**Comment by tfoote** [comment]
+1

**Comment by dirk-thomas** [comment]
lgtm

**Comment by wjwwood** [comment]
Oh, I never opened a pull request for this branch...

https://github.com/ros2/rclcpp/tree/fix_get_type_support_handle

**Comment by wjwwood** [comment]
These are exactly the same changes as mine, lgtm.

**Pull request merged**
