### PR TITLE
Fix lock-order-inversion (potential deadlock)

### PR DESCRIPTION
**Pull request by fujitatomoya**
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>

fix https://github.com/ros2/rclcpp/issues/1121.

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@ivanpauno 

with this fix, i cannot reproduce `lock-order-inversion (potential deadlock)` Thread Sanitizer. Could you check my comments and fix?

**Comment by fujitatomoya** [comment]
http://build.ros2.org/job/Fpr__rclcpp__ubuntu_focal_amd64/92/ does not seem to be related to the fix.

**Comment by ivanpauno** [comment]
> @ivanpauno
> 
> with this fix, i cannot reproduce `lock-order-inversion (potential deadlock)` Thread Sanitizer. Could you check my comments and fix?

Can you explain what the sanitizer was detecting?
Was it an inversion between `graph_mutex_` and [node_graph_interfaces_barrier_mutex_](https://github.com/ros2/rclcpp/blob/87bb9f9758dce239d37256ae91d58ce6325f405b/rclcpp/src/rclcpp/graph_listener.cpp#L141) or [node_graph_interfaces_mutex_](https://github.com/ros2/rclcpp/blob/87bb9f9758dce239d37256ae91d58ce6325f405b/rclcpp/src/rclcpp/graph_listener.cpp#L146) (or something else)?
Was it actually a potential deadlock or just a false positive?

**Comment by fujitatomoya** [comment]
@ivanpauno 

I add explanation here https://github.com/ros2/rclcpp/issues/1121#issuecomment-634680056, if it is not enough, let me know.

> Was it actually a potential deadlock or just a false positive?

I believe it is false positive.

**Comment by ivanpauno** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10914/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6266/)
* macOS [Build Status](https://ci.ros2.org/job/ci_osx/8889/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10816/)

**Pull request merged**
