### PR TITLE
call rclcpp::shutdown() after tests

### PR DESCRIPTION
**Pull request by dirk-thomas**
Might address #863?

### CODE REVIEW

**Comment by dirk-thomas** [comment]
> pending green CI

CI will pass green but that wouldn't answer the question if this change help for the issue. So someone who was able to reproduce it in the past should test it.

**Comment by wjwwood** [comment]
Calling shutdown at the end shouldn't be required... Which problem do you think this will fix? (I skimmed the other issue, but I don't know why you think only calling init is an issue?)

**Comment by dirk-thomas** [comment]
Without a shutdown the node won't communicate to other entities that it is going down.

**Comment by wjwwood** [comment]
Let's consolidate over here: https://github.com/ros2/rclcpp/issues/863#issuecomment-540217007

**Comment by dirk-thomas** [comment]
If others think this isn't necessary I will close the PR.

**Pull request closed without merging**
