### PR TITLE
Fix rclcpp documentation build

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says.There's a long list of issues, in Doxygen and Exhale, yet to be addressed or worked around.

### CODE REVIEW

**Comment by hidmic** [comment]
> 1. Doxygen doesn't like decltype

https://github.com/ros2/rclcpp/pull/1779/commits/a75a468cc2478e86b239e47c7eacfe90c980a2aa solved half of the issue -- Doxygen's C-like lexer needed a gentle push. https://github.com/doxygen/doxygen/pull/8799 takes care of the other half.

**Comment by hidmic** [comment]
https://github.com/ros-infrastructure/rosdoc2/pull/33 and connected PRs resolve the `unabridged (page)` warning.

**Comment by hidmic** [comment]
> 2. Exhale doesn't like SFINAE

We have a problem here. It's not enough to resolve the ambiguity for Exhale. It appears that Breathe is also choking on these template declarations. We _can_ craft completely custom, simplified documentation, but it is less than optimal. See https://github.com/ros2/rclcpp/pull/1779/commits/c23ca1bf58afceb551fc4e065092585ae493c1b1. FYI @clalancette @wjwwood.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2021-10-28/22947/1

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2021-11-18/23209/1

**Comment by clalancette** [comment]
As an update to https://github.com/ros2/rclcpp/pull/1779#issuecomment-951331511 , it looks like we have *most* of that work in.  Still outstanding are:

* https://github.com/svenevs/exhale/pull/117
* https://github.com/svenevs/exhale/pull/136

That said, I was able to generate documentation for rclcpp with this in place and without those two PRs above.  That is, those improve things, but don't fundamentally change the fact that this PR lets the generation proceed.  There are still a bunch of warnings (which the above PRs improve upon), but they are not a blocker.

I'd say we should mark this PR as ready, get it in and then iterate to improve things over time.  @hidmic what do you think?

**Comment by hidmic** [comment]
Sounds good to me @clalancette. Ready for review.

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by hidmic** [comment]
CI up to `rclcpp*` packages:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15899/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10574/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13563/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16214/)

**Comment by hidmic** [comment]
CI's green. Going in!

**Pull request merged**
