### PR TITLE
warning: comparison of integer expressions of different signedness

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/rclcpp/pull/2167#issuecomment-1597197552

### CODE REVIEW

**Comment by fujitatomoya** [comment]
The related code was developed in https://github.com/ros2/rclcpp/pull/2164 and backport humble https://github.com/ros2/rclcpp/pull/2167 detected https://github.com/ros2/rclcpp/pull/2167#issuecomment-1597197552

```bash
In file included from /tmp/ws/src/ros2/rclcpp/rclcpp/test/rclcpp/executors/test_executors.cpp:20:
/tmp/ws/install_isolated/gtest_vendor/src/gtest_vendor/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = unsigned int; T2 = int]’:
/tmp/ws/install_isolated/gtest_vendor/src/gtest_vendor/include/gtest/gtest.h:1554:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper::Compare(const char*, const char*, const T1&, const T2&) [with T1 = unsigned int; T2 = int; typename std::enable_if<((! std::is_integral<_Tp>::value) || (! std::is_pointer<_Dp>::value))>::type* <anonymous> = 0]’
/tmp/ws/src/ros2/rclcpp/rclcpp/test/rclcpp/executors/test_executors.cpp:676:3:   required from ‘void TestIntraprocessExecutors_testIntraprocessRetrigger_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = rclcpp::executors::MultiThreadedExecutor]’
/tmp/ws/src/ros2/rclcpp/rclcpp/test/rclcpp/executors/test_executors.cpp:654:1:   required from here
/tmp/ws/install_isolated/gtest_vendor/src/gtest_vendor/include/gtest/gtest.h:1527:11: warning: comparison of integer expressions of different signedness: ‘const unsigned int’ and ‘const int’ [-Wsign-compare]
 1527 |   if (lhs == rhs) {
      |       ~~~~^~~~~~
/tmp/ws/install_isolated/gtest_vendor/src/gtest_vendor/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/tmp/ws/install_isolated/gtest_vendor/src/gtest_vendor/include/gtest/gtest.h:1554:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; typename std::enable_if<((! std::is_integral<_Tp>::value) || (! std::is_pointer<_Dp>::value))>::type* <anonymous> = 0]’
/tmp/ws/src/ros2/rclcpp/rclcpp/test/rclcpp/executors/test_executors.cpp:697:3:   required from ‘void TestIntraprocessExecutors_testIntraprocessRetrigger_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = rclcpp::executors::MultiThreadedExecutor]’
/tmp/ws/src/ros2/rclcpp/rclcpp/test/rclcpp/executors/test_executors.cpp:654:1:   required from here
/tmp/ws/install_isolated/gtest_vendor/src/gtest_vendor/include/gtest/gtest.h:1527:11: warning: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’ [-Wsign-compare]
```

i think it would be nicer to address this rolling then backporting to iron and humble.

**Review by fujitatomoya — COMMENTED** [review]
I was trying to confirm the original warning but could not.

with `colcon test --event-handlers console_direct+ --abort-on-error --packages-select rclcpp --ctest-args -R test_executors`, it goes `100% tests passed` with this PR.

**Review by clalancette — CHANGES_REQUESTED** [review]
This is really weird.  We have both humble and rolling on the same underlying OS (Ubuntu 22.04), with the same code in place, and one of them has the warning and one does not.  I'm honestly not sure what is going on with that, but we should move forward with a fix.

This fix looks generally correct to me, though I'll also say that we should change everywhere that deals with `callback_count` to use unsigned.  So in the `SetUp`, we should assign it to `0u`, in the callback we should do `fetch_add(1u)`, and when we reset the counter we should do `store(0u)`.  Once those are fixed, and CI is green, I'm happy to approve.

**Comment by fujitatomoya** [comment]
> This is really weird. We have both humble and rolling on the same underlying OS (Ubuntu 22.04), with the same code in place, and one of them has the warning and one does not.

that is what i though too. not sure who this can be detected by CI, cz i cannot reproduce this warning with humble source build.
could be related to https://github.com/ros2/rclcpp/pull/2121? and so https://github.com/ros2/rclcpp/pull/2167 generates the warning?

> though I'll also say that we should change everywhere that deals with callback_count to use unsigned.

makes sense to me. will do that.

**Comment by clalancette** [comment]
> > 
> 
> that is what i though too. not sure who this can be detected by CI, cz i cannot reproduce this warning with humble source build.

Oh, I can reproduce the warning with humble locally.  But I cannot reproduce it with rolling, which is why I think this is super weird.

Regardless, I'm fine with your change here (for both Rolling and Humble), so we can go forward and get this in and then backport it.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19011/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13535/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19764/)

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.

**Comment by fujitatomoya** [comment]
@Mergifyio backport to iron humble

**Comment by fujitatomoya** [comment]
@Mergifyio backport iron humble

**Pull request merged**
