### PR TITLE
Remove deprecated (in c++17 and newer) use of std::allocator<>::rebind

### PR DESCRIPTION
**Pull request by pettni**
Addresses #1655

### CODE REVIEW

**Review by wjwwood — APPROVED** [review]

**Comment by wjwwood** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14675/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9427/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12338/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14818/)

**Comment by SquirrelCZE** [comment]
NOTE: when I applied this it allowed me to compile my project with C++20 and was only patch necessary with ros2 galactic.

**Comment by wjwwood** [comment]
Rerunning CI because I think the macOS warnings were unrelated to this change and were fixed recently:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14685/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9437/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12350/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14828/)

**Comment by wjwwood** [comment]
Thanks @SquirrelCZE!

**Pull request merged**
