### PR TITLE
Added support for std::bind callbacks that have custom arguments

### PR DESCRIPTION
**Pull request by esteve**
This is a quick hack to allow `std::bind` functors that have custom arguments to be passed as callbacks. These changes involve relaxing the rules of `function_traits::same_arguments` to only check if the first N arguments of the `std::bind` functor match the callback signatures, so this has the problem that the `std::bind` might be invalid (e.g. the N+1 argument is a placeholder), the compiler won't complain, but there will be a runtime error.

I've also made a couple of cleanups and implemented two classes for concatenating and slicing `std::tuple`s at compile time.

PR is marked as open, so feel free to edit it to adapt it to your needs.

Addresses #273
Connects to #273

### CODE REVIEW

**Comment by wjwwood** [comment]
Wow, thanks @esteve! It's too bad this stuff isn't in the stdlib, it's pretty hairy stuff.

**Comment by esteve** [comment]
@wjwwood any time! It's unfortunate that we had to implement all this just because of Visual Studio, I wish none of this were necessary :-)

**Comment by dirk-thomas** [comment]
Since these traits have originally been added we have updated the minimum Visual Studio version which I think has a more capable compiler by now. Maybe we should try to go back to less custom traits which might now be supported.

**Comment by wjwwood** [comment]
We can try, but I don't think our version has changed much. There is a vs2017 rc coming up though.

**Comment by esteve** [comment]
According to [this](https://blogs.msdn.microsoft.com/vcblog/2016/06/07/expression-sfinae-improvements-in-vs-2015-update-3/), there were a bunch of improvements in VS2015 Update 3 which might solve the `std::function` ambiguity problem:

> Improvements since Visual Studio 2015 Update 2
> 
> Continued improvements in the quality of our expression SFINAE implementation enabled our Standard Template Library to begin using it in VS 2015 Update 2. Expression SFINAE is used in our implementations of std::function and result_of.

So I created the following example, and it compiles on VS2015 Update 3:

```cpp
#include <functional>

void f(std::function<void(int, int)> arg) {}
void f(std::function<void(int, std::string)> arg) {}

int main(void) {
  auto f1 = [](int, int) -> void {};
  auto f2 = [](int, std::string) -> void {};

  f(f1);
  f(f2);
  return 0;
}
```

the example might be a bit too synthetic, so there's a chance it doesn't reflect the issue here, but it's worth trying removing `function_traits.hpp` and require VS2015 Update 3.

**Comment by dirk-thomas** [comment]
I have updated our Windows slaves so that all of them are using Visual Studio 2015 Update 3. So if anyone would provide a PR we can easily test it.

**Comment by wjwwood** [comment]
@Karsten1987 what do you want to do with this one? Do you need it merged for your pr's to work? Or should we wait until someone has time to see about removing function traits all together?

**Comment by Karsten1987** [comment]
@esteve 's workaround in https://github.com/ros2/rclcpp/issues/273 works for me as for now. The caveats of not using `auto` but explicitly declaring the `std::function` object does the job.

That being said, I am fine with putting this PR on hold and test the VS update at some point.

**Comment by nkoenig** [comment]
This is blocked on seeing if this is fixed on the new VS compiler.

**Comment by esteve** [comment]
@nkoenig unfortunately it's slightly more complex than originally thought. Although VS now properly compiles the snippet I posted, the following does not work on either Clang, GCC or VC++:

```c++
#include <functional>
#include <memory>

struct Message {};

void f(std::function<void(std::shared_ptr<Message>)> arg) {}
void f(std::function<void(std::unique_ptr<Message>)> arg) {}

int main(void) {
  auto f1 = [](std::shared_ptr<Message>) -> void {};
  auto f2 = [](std::unique_ptr<Message>) -> void {};

  f(f1);
  f(f2);
  return 0;
}
```

This produces an ambiguity error with both three compilers:

GCC:
http://rextester.com/COJ12179

Clang:
http://rextester.com/BWISR19029

VC++:
http://rextester.com/RKDX36843

We didn't see this issue when we first wrote the callback code because intraprocess communication used a different API, so there was no ambiguity between `std::unique_ptr` and `std::shared_ptr` (see https://github.com/ros2/rclcpp/commit/b0a2b7610d5b5a2955058774bfd8d36787634e7e). Once `function_traits` was able to deduce more information about a callback, @wjwwood and I unified the `create_subscription` and `create_subscription_with_unique_ptr_callback` methods to provide a cleaner API.

I don't know if there's a better way of achieving this without retorting to the `function_traits` voodoo, I can't seem to force `std::function` not to implicitly convert its arguments to avoid the ambiguity. The same ambiguity issue shows up if you have two functions, one that takes a `std::function<void(int)>` and another one that takes a `std::function<void(long)>`, for example.

**Comment by mikaelarguedas** [comment]
try to review it soon, along https://github.com/ros2/rclcpp/pull/286

**Comment by esteve** [comment]
Let me know if there's anything I can help with to get this and #286
merged. I tried to make the changes as clean as I could, but unfortunately
the code is not very readable anyway :-(

**Comment by allenh1** [comment]
connect to #273

**Comment by mikaelarguedas** [comment]
@allenh1 Tip: waffle parses only the first comment of each issue. So the 'connect to' needs to be added to the first comment

**Comment by Karsten1987** [comment]
I just closed #273. Doing the same here.

**Pull request closed without merging**
