### PR TITLE
added throwing parameter name if parameter is not set

### PR DESCRIPTION
**Pull request by cvbn127**

### CODE REVIEW

**Comment by thomas-moulard** [comment]
Gist: https://gist.githubusercontent.com/thomas-moulard/7c8c01f2e523f5eb1524e70e01dcbefd/raw/5ea686a14c47c19586039eb3874bc455c207d9d8/ros2.repos
BUILD args: --packages-up-to ros2/rclcpp
TEST args: --packages-select ros2/rclcpp
Job: ci_launcher

**Comment by thomas-moulard** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7891/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3941/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6435/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7756/)

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7892/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3942/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6436/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7757/)

**Comment by nuclearsandwich** [comment]
@cvbn127 can you please address the CI failures failures linked above.

**Comment by emersonknapp** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7985/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4005/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6503/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7836/)

**Comment by ivanpauno** [comment]
Superseded by #833.
@cvbn127 again, sorry for the error while pushing in your branch.

**Pull request closed without merging**
