### PR TITLE
remove things that were deprecated during galactic

### PR DESCRIPTION
**Pull request by wjwwood**

### CODE REVIEW

**Comment by wjwwood** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16540/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11126/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16914/)

**Review by jacobperron — APPROVED** [review]

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.  I'll suggest once this is merged, that we immediately do a release to Rolling, and then keep an eye on downstream packages to see what (if anything) fails.

**Comment by wjwwood** [comment]
The CI is green, the failures on Windows are related to CFT pull requests.

**Comment by wjwwood** [comment]
I did a major release because we removed APIs: https://github.com/ros/rosdistro/pull/32716

**Pull request merged**
