### PR TITLE
[dashing backport] reset error message before setting a new one, embed the original one

### PR DESCRIPTION
**Pull request by zmichaels11**
Backport of PR #854 
Signed-off-by: Zachary Michaels <zmichaels11@gmail.com>

### CODE REVIEW

**Comment by zmichaels11** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8202/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4178/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6681/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8079/)

**Comment by tfoote** [comment]
The CI run looks like it didn't select a branch in the repos file for rclcpp.

**Comment by zmichaels11** [comment]
We have a tool that generates the repos file. It currently doesn't support a workflow for backporting so its prone to user error. I'm looking through it right now

**Comment by zmichaels11** [comment]
Ok, fixed the repo selection in the repos file.
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8203/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4180/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6682/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8080/)

**Pull request merged**
