### PR TITLE
Make sure to clean the external client/service handle.

### LINKED ISSUE #1295: Client/Service might be memory leak
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - source
- Version or commit hash:
  - d66cd96f254648de5fa68f6c28a34968563294fb
- DDS implementation:
  - rmw_fastrtps_cpp
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

```
$ colcon build --cmake-args -DCMAKE_BUILD_TYPE=Debug --packages-up-to rclcpp
$ . install/setup.bash
$ valgrind --leak-check=full ./build/rclcpp/test/test_allocator_memory_strategy
```

#### Expected behavior
No memory leak

#### Actual behavior

<details><summary> memory leak log </summary>
<p>

```shell
==1269872== 
==1269872== HEAP SUMMARY:
==1269872==     in use at exit: 57,303 bytes in 167 blocks
==1269872==   total heap usage: 253,411 allocs, 253,244 frees, 94,040,442 bytes allocated
==1269872== 
==1269872== 659 (152 direct, 507 indirect) bytes in 1 blocks are definitely lost in loss record 44 of 53
==1269872==    at 0x483DE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1269872==    by 0x5E7FD35: rmw_create_client (rmw_client.cpp:173)
==1269872==    by 0x50AB1EF: rmw_create_client (functions.cpp:391)
==1269872==    by 0x5070849: rcl_client_init (client.c:169)
==1269872==    by 0x23C1E2: rclcpp::Client<test_msgs::srv::Empty>::Client(rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (client.hpp:219)
==1269872==    by 0x238E06: void __gnu_cxx::new_allocator<rclcpp::Client<test_msgs::srv::Empty> >::construct<rclcpp::Client<test_msgs::srv::Empty>, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(rclcpp::Client<test_msgs::srv::Empty>*, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (new_allocator.h:147)
==1269872==    by 0x236279: void std::allocator_traits<std::allocator<rclcpp::Client<test_msgs::srv::Empty> > >::construct<rclcpp::Client<test_msgs::srv::Empty>, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(std::allocator<rclcpp::Client<test_msgs::srv::Empty> >&, rclcpp::Client<test_msgs::srv::Empty>*, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (alloc_traits.h:484)
==1269872==    by 0x2328BE: std::_Sp_counted_ptr_inplace<rclcpp::Client<test_msgs::srv::Empty>, std::allocator<rclcpp::Client<test_msgs::srv::Empty> >, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(std::allocator<rclcpp::Client<test_msgs::srv::Empty> >, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (shared_ptr_base.h:548)
==1269872==    by 0x22E4EB: std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<rclcpp::Client<test_msgs::srv::Empty>, std::allocator<rclcpp::Client<test_msgs::srv::Empty> >, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(rclcpp::Client<test_msgs::srv::Empty>*&, std::_Sp_alloc_shared_tag<std::allocator<rclcpp::Client<test_msgs::srv::Empty> > >, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (shared_ptr_base.h:679)
==1269872==    by 0x22A515: std::__shared_ptr<rclcpp::Client<test_msgs::srv::Empty>, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<rclcpp::Client<test_msgs::srv::Empty> >, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(std::_Sp_alloc_shared_tag<std::allocator<rclcpp::Client<test_msgs::srv::Empty> > >, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (shared_ptr_base.h:1344)
==1269872==    by 0x22566E: std::shared_ptr<rclcpp::Client<test_msgs::srv::Empty> >::shared_ptr<std::allocator<rclcpp::Client<test_msgs::srv::Empty> >, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(std::_Sp_alloc_shared_tag<std::allocator<rclcpp::Client<test_msgs::srv::Empty> > >, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (shared_ptr.h:359)
==1269872==    by 0x22038E: std::shared_ptr<rclcpp::Client<test_msgs::srv::Empty> > std::allocate_shared<rclcpp::Client<test_msgs::srv::Empty>, std::allocator<rclcpp::Client<test_msgs::srv::Empty> >, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(std::allocator<rclcpp::Client<test_msgs::srv::Empty> > const&, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (shared_ptr.h:702)
==1269872== 
==1269872== 1,858 (432 direct, 1,426 indirect) bytes in 3 blocks are definitely lost in loss record 48 of 53
==1269872==    at 0x483D7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1269872==    by 0x50BFF46: __default_allocate (allocator.c:37)
==1269872==    by 0x50707CA: rcl_client_init (client.c:162)
==1269872==    by 0x23C1E2: rclcpp::Client<test_msgs::srv::Empty>::Client(rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (client.hpp:219)
==1269872==    by 0x238E06: void __gnu_cxx::new_allocator<rclcpp::Client<test_msgs::srv::Empty> >::construct<rclcpp::Client<test_msgs::srv::Empty>, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(rclcpp::Client<test_msgs::srv::Empty>*, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (new_allocator.h:147)
==1269872==    by 0x236279: void std::allocator_traits<std::allocator<rclcpp::Client<test_msgs::srv::Empty> > >::construct<rclcpp::Client<test_msgs::srv::Empty>, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(std::allocator<rclcpp::Client<test_msgs::srv::Empty> >&, rclcpp::Client<test_msgs::srv::Empty>*, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (alloc_traits.h:484)
==1269872==    by 0x2328BE: std::_Sp_counted_ptr_inplace<rclcpp::Client<test_msgs::srv::Empty>, std::allocator<rclcpp::Client<test_msgs::srv::Empty> >, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(std::allocator<rclcpp::Client<test_msgs::srv::Empty> >, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (shared_ptr_base.h:548)
==1269872==    by 0x22E4EB: std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<rclcpp::Client<test_msgs::srv::Empty>, std::allocator<rclcpp::Client<test_msgs::srv::Empty> >, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(rclcpp::Client<test_msgs::srv::Empty>*&, std::_Sp_alloc_shared_tag<std::allocator<rclcpp::Client<test_msgs::srv::Empty> > >, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (shared_ptr_base.h:679)
==1269872==    by 0x22A515: std::__shared_ptr<rclcpp::Client<test_msgs::srv::Empty>, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<rclcpp::Client<test_msgs::srv::Empty> >, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(std::_Sp_alloc_shared_tag<std::allocator<rclcpp::Client<test_msgs::srv::Empty> > >, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (shared_ptr_base.h:1344)
==1269872==    by 0x22566E: std::shared_ptr<rclcpp::Client<test_msgs::srv::Empty> >::shared_ptr<std::allocator<rclcpp::Client<test_msgs::srv::Empty> >, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(std::_Sp_alloc_shared_tag<std::allocator<rclcpp::Client<test_msgs::srv::Empty> > >, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (shared_ptr.h:359)
==1269872==    by 0x22038E: std::shared_ptr<rclcpp::Client<test_msgs::srv::Empty> > std::allocate_shared<rclcpp::Client<test_msgs::srv::Empty>, std::allocator<rclcpp::Client<test_msgs::srv::Empty> >, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(std::allocator<rclcpp::Client<test_msgs::srv::Empty> > const&, rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (shared_ptr.h:702)
==1269872==    by 0x21A1E3: std::shared_ptr<rclcpp::Client<test_msgs::srv::Empty> > std::make_shared<rclcpp::Client<test_msgs::srv::Empty>, rclcpp::node_interfaces::NodeBaseInterface*, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&>(rclcpp::node_interfaces::NodeBaseInterface*&&, std::shared_ptr<rclcpp::node_interfaces::NodeGraphInterface>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_client_options_t&) (shared_ptr.h:718)
==1269872== 
==1269872== 2,469 (408 direct, 2,061 indirect) bytes in 3 blocks are definitely lost in loss record 49 of 53
==1269872==    at 0x483D7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1269872==    by 0x50BFF46: __default_allocate (allocator.c:37)
==1269872==    by 0x50825FB: rcl_service_init (service.c:166)
==1269872==    by 0x23BD70: rclcpp::Service<test_msgs::srv::Empty>::Service(std::shared_ptr<rcl_node_t>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>, rcl_service_options_t&) (service.hpp:204)
==1269872==    by 0x238C03: void __gnu_cxx::new_allocator<rclcpp::Service<test_msgs::srv::Empty> >::construct<rclcpp::Service<test_msgs::srv::Empty>, std::shared_ptr<rcl_node_t>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&>(rclcpp::Service<test_msgs::srv::Empty>*, std::shared_ptr<rcl_node_t>&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&) (new_allocator.h:147)
==1269872==    by 0x2360B1: void std::allocator_traits<std::allocator<rclcpp::Service<test_msgs::srv::Empty> > >::construct<rclcpp::Service<test_msgs::srv::Empty>, std::shared_ptr<rcl_node_t>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&>(std::allocator<rclcpp::Service<test_msgs::srv::Empty> >&, rclcpp::Service<test_msgs::srv::Empty>*, std::shared_ptr<rcl_node_t>&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&) (alloc_traits.h:484)
==1269872==    by 0x2325AE: std::_Sp_counted_ptr_inplace<rclcpp::Service<test_msgs::srv::Empty>, std::allocator<rclcpp::Service<test_msgs::srv::Empty> >, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<std::shared_ptr<rcl_node_t>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&>(std::allocator<rclcpp::Service<test_msgs::srv::Empty> >, std::shared_ptr<rcl_node_t>&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&) (shared_ptr_base.h:548)
==1269872==    by 0x22E1D5: std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<rclcpp::Service<test_msgs::srv::Empty>, std::allocator<rclcpp::Service<test_msgs::srv::Empty> >, std::shared_ptr<rcl_node_t>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&>(rclcpp::Service<test_msgs::srv::Empty>*&, std::_Sp_alloc_shared_tag<std::allocator<rclcpp::Service<test_msgs::srv::Empty> > >, std::shared_ptr<rcl_node_t>&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&) (shared_ptr_base.h:679)
==1269872==    by 0x22A2DD: std::__shared_ptr<rclcpp::Service<test_msgs::srv::Empty>, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<rclcpp::Service<test_msgs::srv::Empty> >, std::shared_ptr<rcl_node_t>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&>(std::_Sp_alloc_shared_tag<std::allocator<rclcpp::Service<test_msgs::srv::Empty> > >, std::shared_ptr<rcl_node_t>&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&) (shared_ptr_base.h:1344)
==1269872==    by 0x225440: std::shared_ptr<rclcpp::Service<test_msgs::srv::Empty> >::shared_ptr<std::allocator<rclcpp::Service<test_msgs::srv::Empty> >, std::shared_ptr<rcl_node_t>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&>(std::_Sp_alloc_shared_tag<std::allocator<rclcpp::Service<test_msgs::srv::Empty> > >, std::shared_ptr<rcl_node_t>&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&) (shared_ptr.h:359)
==1269872==    by 0x2200E6: std::shared_ptr<rclcpp::Service<test_msgs::srv::Empty> > std::allocate_shared<rclcpp::Service<test_msgs::srv::Empty>, std::allocator<rclcpp::Service<test_msgs::srv::Empty> >, std::shared_ptr<rcl_node_t>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&>(std::allocator<rclcpp::Service<test_msgs::srv::Empty> > const&, std::shared_ptr<rcl_node_t>&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&) (shared_ptr.h:702)
==1269872==    by 0x219D29: std::shared_ptr<rclcpp::Service<test_msgs::srv::Empty> > std::make_shared<rclcpp::Service<test_msgs::srv::Empty>, std::shared_ptr<rcl_node_t>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&>(std::shared_ptr<rcl_node_t>&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::AnyServiceCallback<test_msgs::srv::Empty>&, rcl_service_options_t&) (shared_ptr.h:718)
==1269872== 
==1269872== LEAK SUMMARY:
==1269872==    definitely lost: 992 bytes in 7 blocks
==1269872==    indirectly lost: 3,994 bytes in 53 blocks
==1269872==      possibly lost: 0 bytes in 0 blocks
==1269872==    still reachable: 52,317 bytes in 107 blocks
==1269872==         suppressed: 0 bytes in 0 blocks
==1269872== Reachable blocks (those to which a pointer was found) are not shown.
==1269872== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==1269872== 
==1269872== For lists of detected and suppressed errors, rerun with: -s
==1269872== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)


```

</p>
</details>

#### Additional information

It can't make sure client handle is destructed before the node handle if this client handle is stored at external.
https://github.com/ros2/rclcpp/blob/d66cd96f254648de5fa68f6c28a34968563294fb/rclcpp/src/rclcpp/client.cpp#L69-L70

There are two ways to solve this memory leak.

- make sure [service/client] handle stored at external is clean before calling `ClientBase::~ClientBase`.

- put share_ptr(node_handle_) inside deleter of `[service/client]_handle_`,  it will make sure [service/client] handle is destructed before the node handle
I do like this method because it will make users not to care which variable should be destroyed first if using `get_[service/client]_handle()` outside.

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
Fixes #1295

Signed-off-by: Chen Lihui <Lihui.Chen@sony.com>

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm, but this fix does not exactly related to memory leak detected on https://github.com/ros2/rclcpp/issues/1295#issue-697564194.

**Comment by iuhilnehc-ynos** [comment]
@fujitatomoya 

Thanks for your review.
I'll look into it and share my understanding later.

**Comment by iuhilnehc-ynos** [comment]
@fujitatomoya 

> but this fix does not exactly related to memory leak detected on #1295 (comment).

I don't know why `valgrind` not show the correct location and full backtrace.
```
==1269872==    at 0x483DE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1269872==    by 0x5E7FD35: rmw_create_client (rmw_client.cpp:173) 
==1269872==    by 0x50AB1EF: rmw_create_client (functions.cpp:391)
==1269872==    by 0x5070849: rcl_client_init (client.c:169)
```
I checked https://github.com/ros2/rmw_fastrtps/blob/4dc737955d8d08db3e1e3c410a70ee5343c50cf5/rmw_fastrtps_cpp/src/rmw_client.cpp#L173
it will be destroyed if there is an error inside this function
https://github.com/ros2/rmw_fastrtps/blob/4dc737955d8d08db3e1e3c410a70ee5343c50cf5/rmw_fastrtps_cpp/src/rmw_client.cpp#L264-L266

But I got some following log about client/service, such as
```
[ RUN      ] TestAllocatorMemoryStrategy.number_of_entities_with_service
[ERROR] [1600310833.221629134] [rclcpp]: Error in destruction of rcl service handle: the Node Handle was destructed too early. You will leak memory
[       OK ] TestAllocatorMemoryStrategy.number_of_entities_with_service (10960 ms)
[ RUN      ] TestAllocatorMemoryStrategy.number_of_entities_with_client
[ERROR] [1600310833.657386335] [rclcpp]: Error in destruction of rcl client handle: the Node Handle was destructed too early. You will leak memory
[       OK ] TestAllocatorMemoryStrategy.number_of_entities_with_client (425 ms)
```

ex.

- test case

```
TEST_F(TestAllocatorMemoryStrategy, number_of_entities_with_service) {
   auto node_with_service = create_node_with_service("service_node");
}
```

- `create_node_with_service` put service into a member variable `services_` of TestAllocatorMemoryStrategy

```
   services_.push_back(node_with_service->create_service<test_msgs::srv::Empty>)          // put service into a member variable, notice that services_ have a shared_ptr of node_handle_ in `ServiceBase`
```

- AllocatorMemoryStrategy members

```
  VectorRebind<std::shared_ptr<const rcl_service_t>> service_handles_;
  VectorRebind<std::shared_ptr<const rcl_client_t>> client_handles_;
```

- members definition order of TestAllocatorMemoryStrategy

```
  std::shared_ptr<AllocatorMemoryStrategy<>> allocator_memory_strategy_;

  std::vector<rclcpp::ServiceBase::SharedPtr> services_;
  std::vector<rclcpp::ClientBase::SharedPtr> clients_;
```

it means `services_/clients_` will be destroyed before allocator_memory_strategy_

this is the issue here. `services_` (including `node_handle_`) is destroyed before `allocator_memory_strategy_`.
(NOTE: it's a little complicated here.)

- summary

```
TestAllocatorMemoryStrategy ctor
  number_of_entities_with_service
  SetUp
     allocator_memory_strategy_ = std::make_shared<AllocatorMemoryStrategy<>>(allocator_);

  node ctor
     service ctor
     allocator_memory_strategy.collect_entities
           service_handles_.push_back(service->get_service_handle());
  node dtor

  TearDown

TestAllocatorMemoryStrategy dtor
  service dtor                                        // notice that `node_handler_` will be destoryed here 
  allocator_memory_strategy dtor        // service_handles_ still process `service->get_service_handle()`
                                                            // which will call deleted of `service_handle`
```

How to break dependency?
One method is to put `allocator_memory_strategy_.reset();` into `TearDown`.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12579/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7547/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10292/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12504/)

**Pull request merged**
