### PR TITLE
Add rclcpp_action action_server benchmarks

### PR DESCRIPTION
**Pull request by brawner**
This PR adds benchmarks for rclcpp_action's action server.

Building with benchmarks and testing `--packages-select rclcpp_action`
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12930/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7882/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10649/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12880/)

Signed-off-by: Stephen Brawner <brawner@gmail.com>

### CODE REVIEW

**Comment by brawner** [comment]
Cancel goal benchmark is failing currently for some reason, so I need to debug that, but I thought it would be helpful to get some initial feedback on this PR.

```
----------------------------------------------------------------------------------------------------------------------
Benchmark                                                            Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------------------------------------------------
ActionServerPerformanceTest/construct_server_without_client     395762 ns       393917 ns         1732 heap_allocations=561.804
ActionServerPerformanceTest/construct_server_with_client        480011 ns       477238 ns         1501 heap_allocations=715.023
ActionServerPerformanceTest/destroy_server                      388775 ns       313155 ns         2140 heap_allocations=714.492
ActionServerPerformanceTest/action_server_accept_goal           605445 ns       457998 ns         2656 heap_allocations=110.758
ActionServerPerformanceTest/action_server_cancel_goal       ERROR OCCURRED: 'Cancel request did not succeed'
ActionServerPerformanceTest/action_server_execute_goal          545994 ns       545802 ns        10570 heap_allocations=119.1
ActionServerPerformanceTest/action_server_set_success           500492 ns       500318 ns         8609 heap_allocations=117.078
ActionServerPerformanceTest/action_server_abort                 447334 ns       447172 ns         9135 heap_allocations=117.217
```

**Review by ahcorde — APPROVED** [review]

**Comment by brawner** [comment]
I think I was able to address the above bug
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12947/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7896/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10664/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12896/)

**Comment by brawner** [comment]
Addressed a couple of issues that only Windows seemed to care about.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12948/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7897/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10665/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12897/)

**Comment by brawner** [comment]
Interestingly, MSVC doesn't seem to handle constexpr variables appropriately with respect to lambda captures. Anyway, Clang and MSVC disagree about the resolution. I hope the most recent commit is something they can agree on

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12948/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7897/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10665/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12897/)

**Comment by brawner** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12952/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7900/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10668/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12900/)

**Pull request merged**
