### PR TITLE
Add functions to dump ParameterVariants to json encoded strings

### PR DESCRIPTION
**Pull request by tfoote**
This is a first step toward creating tests which can assert the expected values of parameters in json for easy debugging and comparison.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
@tfoote what is the status on this ?

**Comment by tfoote** [comment]
These functions were a start toward being able to dump the parameter state to json so that we could easily write unit tests with the expected serialized json result in a file and assert they match. This was deprioritized so this implementation exists but the remainder of the testing capabilities were not implemented to test this.

**Comment by ivanpauno** [comment]
@tfoote this sounds a bit outdated, can it be closed?

**Comment by tfoote** [comment]
We can close this. There's nothing fundamental or ground breaking in this PR but it's a long way from being feature complete. Hopefully someone might find this and pick up the idea in the future. There are use cases but right now they're not pressing.

**Pull request closed without merging**
