### PR TITLE
Update get_parameter_from_event to follow the function description

### PR DESCRIPTION
**Pull request by Barry-Xu-2018**
Address #1921

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
looks good to me.

**Review by alsora — APPROVED** [review]

**Review by Treborsky — APPROVED** [review]
lgtm

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16606/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11190/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16996/)

**Review by jacobperron — APPROVED** [review]
LGTM

**Pull request merged**
