### PR TITLE
Add throwing parameter name if parameter is not set

### PR DESCRIPTION
**Pull request by ivanpauno**
Continuing https://github.com/ros2/rclcpp/pull/815, as I break the original branch

### CODE REVIEW

**Comment by prajakta-gokhale** [comment]
Gist: https://gist.githubusercontent.com/prajakta-gokhale/02facb5e06cc7b21d2891f125a42a873/raw/8026473ec02fa3a3a2911fb6be38b4e2be9ed995/ros2.repos
BUILD args: --packages-up-to rclcpp
TEST args: --packages-select rclcpp
Job: ci_launcher

**Comment by prajakta-gokhale** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8049/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4056/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6556/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7919/)

**Comment by cvbn127** [comment]
@prajakta-gokhale as you can see, Jenkins says: "Package 'ros2/rclcpp' specified with --packages-up-to was not found". 
I'm not sure but maybe you should build with **--packages-up-to rclcpp** ?

**Comment by prajakta-gokhale** [comment]
@cvbn127 you're right. Restarted with the right package name.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8055/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4062/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6561/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7925/)

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8093/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4094/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/6594/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/7969/)

**Pull request merged**
