### PR TITLE
fix one subscription can wait_for_message twice

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
to fix https://github.com/ros2/rclcpp/issues/1864

Signed-off-by: Chen Lihui <lihui.chen@sony.com>

### CODE REVIEW

**Review by alsora — APPROVED** [review]

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Review by clalancette — APPROVED** [review]
Looks good with green CI.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15996/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10665/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16322/)

**Comment by clalancette** [comment]
Going ahead and merging this one that was approved and has green CI.

**Pull request merged**
