### PR TITLE
[foxy backport] Derive and throw exception in spin_some spin_all for StaticSingleThreadedExecutor

### PR DESCRIPTION
**Pull request by brawner**
This PR replaces #1229 in favor of a solution that doesn't affect ABI compatibility, but accomplishes a similar result.

Edit: This backports #1220 to foxy

### CODE REVIEW

**Comment by brawner** [comment]
@jacobperron @clalancette This is an older issue, but you both provided good feedback on the original PRs.

**Review by jacobperron — APPROVED** [review]
Looks okay to me. I'd like @clalancette to take a look too though.

**Comment by brawner** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12642/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7603/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10351/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12573/)

**Review by clalancette — APPROVED** [review]
Clever solution to maintain ABI.

**Comment by brawner** [comment]
I'm merging this into https://github.com/ros2/rclcpp/tree/brawner/rclcpp-backport-tests-part1 which will act as a feature branch, not into foxy directly yet.

**Pull request merged**
