### PR TITLE
Added Missing Std exceptions to some files

### PR DESCRIPTION
**Pull request by Imeguras**
On Arch Linux the build was failing because some includes were missing this should fix the problem

### CODE REVIEW

**Comment by Imeguras** [comment]
Added a sign message

**Comment by alsora** [comment]
@Imeguras can you redirect the PR towards the `rolling` branch? Then changes can be backported to old releases

**Comment by Imeguras** [comment]
I redirected it, however i havent tested it i will try to do so now

**Comment by Imeguras** [comment]
@alsora you meant chaging the base branch? or do you want me to go to rolling and then do the changes?

**Comment by Imeguras** [comment]
rolling back as some conflicts appeared

**Comment by fujitatomoya** [comment]
@Imeguras i changed the base target branch to `rolling`, there are many conflicts come up. can you check and rebase your branch based on `rolling`?

**Comment by Imeguras** [comment]
Since fixing the conflict would probably do more harm than good i've decided to create a new PR to address the issue

**Pull request closed without merging**
