### PR TITLE
Pass const references to parameters client API

### LINKED ISSUE #141: parameter client: pass vectors by reference
I noticed this while combing through the rclcpp library PR, but I wanted to make note of it here: we should pass std::vectors and other potentially large objects by reference. There are a few places where this is not done in `parameter_client` and possibly elsewhere.

### PR DESCRIPTION
**Pull request by esteve**
Pass vector by reference

Fixes #141

### CODE REVIEW

**Comment by wjwwood** [comment]
Please hold off on this until we've merged the library branches (or until we've decided they are further delayed) as it will conflict.

**Comment by esteve** [comment]
@wjwwood no problem, I've also cancelled the CI jobs.

**Comment by dirk-thomas** [comment]
+1 on the patch itself.

**Comment by esteve** [comment]
CI jobs:

http://ci.ros2.org/view/All/job/ros2_batch_ci_linux/530/
http://ci.ros2.org/view/All/job/ros2_batch_ci_osx/401/
http://ci.ros2.org/view/All/job/ros2_batch_ci_windows/555/

**Comment by esteve** [comment]
Merging, the Windows CI job passed for OpenSplice and the tests pass locally on Linux.

**Pull request merged**
