### PR TITLE
add version of create_subscription which just takes queue size and not a qos profile

### PR DESCRIPTION
**Pull request by wjwwood**
Connects to ros2/design#56.

### CODE REVIEW

**Comment by wjwwood** [comment]
CI:
- http://ci.ros2.org/job/ros2_batch_ci_linux/437/
- http://ci.ros2.org/job/ros2_batch_ci_osx/346/
- http://ci.ros2.org/job/ros2_batch_ci_windows/488/

**Comment by wjwwood** [comment]
CI is good, up for review.

**Comment by wjwwood** [comment]
Also up for review is this one: https://github.com/ros2/system_tests/pull/56

**Comment by dirk-thomas** [comment]
+1

In the future I think we should have a one set of method (which is as small as possible) providing the core functionality. And beside that a separate set of methods which are only syntactic sugar and reusing the core functionality internally but expose a different interface.

**Pull request merged**
