### PR TITLE
use reinterpret_cast for function pointer conversion.

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/rclcpp/issues/1915

Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
https://github.com/ros2/rclcpp/pull/1263 subscription callbacks do not have this problem, that has been verified with https://github.com/fujitatomoya/ros2_test_prover/blob/3f8005350d75b0da30bad734252966d7c6868ca1/prover_rclcpp/src/rclcpp_1915.cpp#L27-L31

**Review by christophebedard — APPROVED** [review]
LGTM.

**Comment by christophebedard** [comment]
> #1263 subscription callbacks do not have this problem, that has been verified with [fujitatomoya/ros2_test_prover@`3f80053`/prover_rclcpp/src/rclcpp_1915.cpp#L27-L31](https://github.com/fujitatomoya/ros2_test_prover/blob/3f8005350d75b0da30bad734252966d7c6868ca1/prover_rclcpp/src/rclcpp_1915.cpp#L27-L31)

Yeah, if I remember correctly, function pointers and `std::bind`s all get converted into `std::function`.

**Review by fujitatomoya — COMMENTED** [review]
@christophebedard thanks for review, i will start the CI.

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16573/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11157/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16961/)

**Comment by fujitatomoya** [comment]
@sloretz @clalancette could you review this when you have time?

**Review by clalancette — APPROVED** [review]
This looks very reasonable to me.  Let's wait to merge this until after we branch off for Humble (probably today).

**Pull request merged**
