### PR TITLE
!fix(Client): Do not hold goal_handle ptr if result cb is set.

### PR DESCRIPTION
**Pull request by jmachowinski**
The capture of the lambda held an copy of the shared_ptr to the goal handle. This lead to the behavior that the goal callbacks would be called, even though the user dropped the handle.

Note, this will break the current tutorial, as it restores the documented behavior that a goal will be invalidated as soon as one drops the handle.

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos can you do 2nd review? i think we can backport this to iron and humble.

**Comment by iuhilnehc-ynos** [comment]
> This lead to the behavior that the goal callbacks would be called, even though the user dropped the handle.

From my point of view, this PR doesn't totally fix the issue that the user's callback could be called if the user dropped the handle.

[goal_handle->set_result(wrapped_result);](https://github.com/ros2/rclcpp/blob/5870033007e27fd9f7940ba9bd5e83b47754a783/rclcpp_action/include/rclcpp_action/client.hpp#L743) -> [result_callback_(wrapped_result);](https://github.com/ros2/rclcpp/blob/bf1396b272782e007df7e0f89cb4c6d94452c848/rclcpp_action/include/rclcpp_action/client_goal_handle_impl.hpp#L77) if the user drop the goal_handle after [typename GoalHandle::SharedPtr goal_handle_ = goal_handles_[goal_id].lock();](https://github.com/ros2/rclcpp/blob/5870033007e27fd9f7940ba9bd5e83b47754a783/rclcpp_action/include/rclcpp_action/client.hpp#L725) is not nullptr.

I think there is a method to fix the issue without this PR.
`GoalHandle::SharedPtr` should be only managed on the user side, not in the https://github.com/ros2/rclcpp/blob/6815022909086487f2b8dc14c0540b00d4cf61a0/rclcpp_action/include/rclcpp_action/client.hpp#L757 since it could be held inside the `rclcpp_action`. The key is to use an extra level(object) of indirect in `rclcpp_action`, which member methods can be called in the destructor of `GoalHandle`.

**Comment by jmachowinski** [comment]
> > This lead to the behavior that the goal callbacks would be called, even though the user dropped the handle.
> 
> From my point of view, this PR doesn't totally fix the issue that the user's callback could be called if the user dropped the handle.
> 
> [goal_handle->set_result(wrapped_result);](https://github.com/ros2/rclcpp/blob/5870033007e27fd9f7940ba9bd5e83b47754a783/rclcpp_action/include/rclcpp_action/client.hpp#L743) -> [result_callback_(wrapped_result);](https://github.com/ros2/rclcpp/blob/bf1396b272782e007df7e0f89cb4c6d94452c848/rclcpp_action/include/rclcpp_action/client_goal_handle_impl.hpp#L77) if the user drop the goal_handle after [typename GoalHandle::SharedPtr goal_handle_ = goal_handles_[goal_id].lock();](https://github.com/ros2/rclcpp/blob/5870033007e27fd9f7940ba9bd5e83b47754a783/rclcpp_action/include/rclcpp_action/client.hpp#L725) is not nullptr.
> 
This is correct, see https://github.com/ros2/rclcpp/pull/2281

Anyhow this fixes commit fixes a part of the issue and is obviously a bug. Therefore I would like to see it merged, before we continue the lengthy discussion on how to fix the complete issue for real.

**Comment by jmachowinski** [comment]
> But there still exists the bug after applying this PR. What if further discussion doesn't need this PR for this issue, why should we merge it first?

This mostly comes down to it fixes 99% of the issue and is a step in the correct direction. This also restores the documented behaviour, that the user needs to hold the goal handle, in order for the action to succeed.
But if the consensus is that we need to get it perfect before merge, I am also fine with this.
 
> 
> I agree with clalancette on the `make this more automatic` mentioned at [#2281 (comment)](https://github.com/ros2/rclcpp/pull/2281#discussion_r1307354723), rather than calling `drop_goal_handle()` manually.

Can you then comment on https://github.com/ros2/rclcpp/pull/2281#discussion_r1307819954 ?

If I know the direction, this should go, I can implement it, and get it off my table ;-P

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos 
CC: @jmachowinski 

that was my suggestion to separate this PR to merge, i think this can be handled with another problem. actually i was thinking that we should backport this to iron and humble, for doing so separating PR would be much better to fix the specific problem w/o breaking ABI.

> I agree with clalancette on the make this more automatic mentioned at https://github.com/ros2/rclcpp/pull/2281#discussion_r1307354723, rather than calling drop_goal_handle() manually.

yeah, i think we all are on the same page. let's post the idea on https://github.com/ros2/rclcpp/pull/2281#discussion_r1307819954 instead.

**Comment by fujitatomoya** [comment]
that also sounds good to me 👍

**Comment by iuhilnehc-ynos** [comment]
@fujitatomoya 

OK, Let's improve it step by step.

@jmachowinski 

It seems we can merge this PR into `rolling`. Before running CI, could you address https://github.com/ros2/demos/blob/bd49f4b64ee7f65616dccbe37e96fb64a9cad6ee/action_tutorials/action_tutorials_cpp/src/fibonacci_action_client.cpp#L76 and [the document](https://github.com/ros2/rclcpp/blob/6815022909086487f2b8dc14c0540b00d4cf61a0/rclcpp_action/include/rclcpp_action/client.hpp) as well?

**Comment by jmachowinski** [comment]
@iuhilnehc-ynos 
> It seems we can merge this PR into `rolling`. Before running CI, could you address https://github.com/ros2/demos/blob/bd49f4b64ee7f65616dccbe37e96fb64a9cad6ee/action_tutorials/action_tutorials_cpp/src/fibonacci_action_client.cpp#L76

Done

> and [the document](https://github.com/ros2/rclcpp/blob/6815022909086487f2b8dc14c0540b00d4cf61a0/rclcpp_action/include/rclcpp_action/client.hpp#L411) as well?

I don't see anything that is wrong with the documentation.

I was wondering, if we should add [[nodiscard]] to async_send_goal

**Comment by clalancette** [comment]
The fact that we had to open up https://github.com/ros2/demos/pull/649 means we are breaking user semantics.  Because of that, I don't think we should merge this in until we know the full shape of the solution.

Put another way, we *can* break API/semantics to fix bugs (though I will always push for a "deprecation" cycle if at all possible).  But what I don't think we should do is to break API/semantics for a partial fix, and then have to do it again once we have the full fix.  If we are going to have to break API/semantics, we should do it all in one go and let the community know.

**Comment by jmachowinski** [comment]
Closing in favor for https://github.com/ros2/rclcpp/pull/2281

**Pull request closed without merging**
