### PR TITLE
[dashing backport] Fixed "memory leak" in action clients (#920)

### PR DESCRIPTION
**Pull request by ivanpauno**
Backport of #920.

### CODE REVIEW

**Comment by sloretz** [comment]
@ivanpauno mind signing off the cherry-picked commit? I think `git commit --amend -s` will do it.

**Comment by sloretz** [comment]
@ros-pull-request-builder retest this please

**Comment by sloretz** [comment]
@ros-pull-request-builder retest this please

**Comment by sloretz** [comment]
@nuclearsandwich are these known flaky tests on the `dashing` branch? The PR job failures have been inconsistent. The latest job passes though.


250. http://build.ros2.org/job/Dpr__rclcpp__ubuntu_bionic_amd64/250/
  * `rclcpp_components.TestComponentManager.load_components`
251. http://build.ros2.org/job/Dpr__rclcpp__ubuntu_bionic_amd64/251/
  * `rclcpp.TestWithDifferentNodeOptions/TestPublisherSubscriptionCount.increasing_and_decreasing_counts/two_subscriptions_intraprocess_comm (two_subscriptions_intraprocess_comm)`
  * `rclcpp.TestWithDifferentNodeOptions/TestPublisherSubscriptionCount.increasing_and_decreasing_counts/two_subscriptions_one_intraprocess_one_not (two_subscriptions_one_intraprocess_one_not)`
  * `rclcpp.TestWithDifferentNodeOptions/TestPublisherSubscriptionCount.increasing_and_decreasing_counts/two_subscriptions_in_two_contexts_with_intraprocess_comm (two_subscriptions_in_two_contexts_with_intraprocess_comm)`

**Comment by sloretz** [comment]
CI (dashing, testing just rclcpp_action)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8807/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4623/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7222/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8723/)

**Comment by dirk-thomas** [comment]
> are these known flaky tests on the `dashing` branch?

See the history on the `dev` job: http://build.ros2.org/job/Ddev__rclcpp__ubuntu_bionic_amd64/

It also had the failing tests but a retrigger passed green - so it looks like a flaky test.

**Comment by ivanpauno** [comment]
> 250. http://build.ros2.org/job/Dpr__rclcpp__ubuntu_bionic_amd64/250/

Similar to this https://github.com/ros2/build_cop/issues/184, though it's failing in another part of the test.
Also, this patch is completely unrelated with the failure.

> 251.

I don't remember those failures, but it seems to be completely unrelated to this patch.

**Comment by sloretz** [comment]
CI looks good. Merging so I can make a release.

**Pull request merged**
