### PR TITLE
Add Executor::spin_some

### PR DESCRIPTION
**Pull request by jacquelinekay**
Add `spin_some`, which executes all available executors until none are available without blocking. Similar to `spin_node_some` but without the messy add/remove node logic.

### CODE REVIEW

**Comment by wjwwood** [comment]
We have to consider the sub classes of executor.

I think this might need to be pure virtual and then have it be implemented differently in SingleThreadedExecutor and MultiThreadedExecutor. For instance, I'm not sure how the multi threaded one should handle spin some.

**Comment by jacquelinekay** [comment]
K, sounds good. What about the existing implementation of `spin_node_some`? It seems to be specialized for a SingleThreadedExecutor, but it's not virtual.

**Comment by jacquelinekay** [comment]
I've decided to make `spin_some` virtual with a default implementation, and I've recorded the issue to implement `spin_some` for `MultiThreadeExecutor` here: ros2/rclcpp/issues/85

**Comment by wjwwood** [comment]
lgtm

**Comment by esteve** [comment]
+1

**Comment by dirk-thomas** [comment]
+1

**Pull request merged**
