### PR TITLE
Enable callback group tests for connextdds

### PR DESCRIPTION
**Pull request by cwecht**
Depends on https://github.com/ros2/rmw_connextdds/pull/76

### CODE REVIEW

**Comment by alsora** [comment]
There are disabled tests also here:
 - https://github.com/ros2/rclcpp/blob/rolling/rclcpp/test/rclcpp/executors/test_events_executor.cpp
 - https://github.com/ros2/rclcpp/blob/rolling/rclcpp/test/rclcpp/executors/test_executors.cpp

**Review by fujitatomoya — COMMENTED** [review]
change for this file looks good to me.

in addition to https://github.com/ros2/rclcpp/pull/2182#issuecomment-1531705727, https://github.com/ros2/rclcpp/blob/rolling/rclcpp/test/rclcpp/test_qos_event.cpp needs to be also update since https://github.com/ros2/rmw_connextdds/pull/76/ supports `rmw_event_set_callback()`?

**Comment by mjcarroll** [comment]
@cwecht when you reenable the tests discussed above, ping me and I will run CI.

**Comment by cwecht** [comment]
@mjcarroll the tests are reenabled now. They revealed an issue in rmw_connextdds which hopefully is fixed in https://github.com/ros2/rmw_connextdds/pull/116 . However, on may machine these test have been rather flaky. I'm not quite sure wheather this is an issue of my machine or an issue of the implementation.

**Comment by alsora** [comment]
Can you post some logs of the failures?
Are these failures with connextdds or also with other RMWs?

**Comment by alsora** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18656/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13183/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19384/)

**Comment by alsora** [comment]
CI with repos https://gist.github.com/alsora/cc8234e7b33b1996db9e1e9adc075f17

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18658/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13185/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19386/)

**Comment by cwecht** [comment]
> Can you post some logs of the failures? Are these failures with connextdds or also with other RMWs?

As far as I can tell, there are no issues with the other RMWs. Failing tests are:
- TestQosEvent.test_pub_matched_event_by_set_event_callback
- TestQosEvent.test_pub_matched_event_by_option_event_callback

This might be due to the fact that I tried to retro fit the subscription/publication matched events with https://github.com/ros2/rmw_connextdds/pull/116 . Probably I just missed something there.

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by alsora** [comment]
I'm starting a new Linux CI to see if tests are stable enough

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18668/)

**Comment by cwecht** [comment]
`test_node_interfaces__node_graph` seems to be be the only test remaning to fail, right? I can not reprocude that error on my  machine though. Maybe this failure is more realted to the test environment on the server?

**Comment by alsora** [comment]
@cwecht have you tried running the test multiple times while stressing your CPU?

**Comment by cwecht** [comment]
@alsora I just ran the test in a docker container with quite restricted resources and the test still succeeds. Is it possible that in the CI/CD pipeline there are multiple tests concurrently and interfering with each other? This could explain why the test are failing because of too many names and namespaces.

**Comment by clalancette** [comment]
> Is it possible that in the CI/CD pipeline there are multiple tests concurrently and interfering with each other?

So we are careful to run only one test at a time in CI:

```
PYTHONIOENCODING=utf_8 PYTHONUNBUFFERED=1 colcon test --build-base build_isolated --install-base install_isolated --test-result-base test_results --event-handlers console_direct+ --executor sequential --test-result-base /tmp/ws/test_results
```

(notice `--executor sequential`)

I guess there is some possibility of something else being in the network, but in theory every test container is in an isolated network.

There are two things to do here:
1.  I'll kick off a new Rpr build just to see if that was a one-off flake.
2.  If that still fails, then I would say the next step here is to see if the current head of Rolling has similar problems.

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Comment by cwecht** [comment]
@clalancette If I get the documentation right, `--executor sequential` only processes one package after the other, but the test in each package may run cuncurrently. Maybe `--parallel-workers 1` is worth a try?

**Comment by clalancette** [comment]
> @clalancette If I get the documentation right, `--executor sequential` only processes one package after the other, but the test in each package may run cuncurrently.

I guess it is possible in theory, but ctest only runs thing sequentially by default (as far as I know).

**Comment by cwecht** [comment]
> > @clalancette If I get the documentation right, `--executor sequential` only processes one package after the other, but the test in each package may run cuncurrently.
> 
> I guess it is possible in theory, but ctest only runs thing sequentially by default (as far as I know).

hm, it seems, that this is basically a ctest parameter. ctest has `-j`/`--parallel`: https://cmake.org/cmake/help/latest/manual/ctest.1.html#cmdoption-ctest-j I don't know the default though. But I remember that we had similar issue which could be fixed by setting `--parallel-workers 1`.

**Comment by cwecht** [comment]
Ok, I had another look at it. With the most recent fixes for test_qos_event should have stabalized them.
Sometimes,  the subscriber_triggered_to_receive_message tests from test_add_callback_groups_to_executor. However, these tests are failing at times with the rolling branch  of rmw_connextdds, too. So it seems, that the flakyness of those tests are not related to https://github.com/ros2/rmw_connextdds/pull/76 .

**Comment by cwecht** [comment]
The most recent build failed becaus of an issue with the CI/CD toolchain, I suppose. @clalancette I suggest to trigger a new run :)

**Comment by clalancette** [comment]
> The most recent build failed becaus of an issue with the CI/CD toolchain, I suppose. @clalancette I suggest to trigger a new run :)

Sigh, yeah, that was Ubuntu going out to lunch for a few hours.

@ros-pull-request-builder retest this please

**Comment by mjcarroll** [comment]
Are we now confident that these tests aren't flaking?

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18842/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13382/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19594/)

**Comment by cwecht** [comment]
Looks like the most recent build failed (again) because of toolchain issues, right?

**Comment by clalancette** [comment]
> Looks like the most recent build failed (again) because of toolchain issues, right?

It looks like a branch it was expecting didn't exist.  @mjcarroll can you take a look?

**Comment by cwecht** [comment]
Ok, from my point of view these test failures are caused by either a tooling issue(on Linux non-aarch64, I'm actually not quite sure what went wrong here) or a "flaky test" which has not been touched within this PR.

**Comment by clalancette** [comment]
> tooling issue(on Linux non-aarch64, I'm actually not quite sure what went wrong here) 

Yeah, that was a node going away.  I've restarted it.

> or a "flaky test" which has not been touched within this PR.

Yeah, it looks like that Windows one is a flake: https://ci.ros2.org/view/nightly/job/nightly_win_rel/2705/

So if Linux amd64 comes back green, we can go ahead with this.

**Comment by cwecht** [comment]
hm, I guess a `java.nio.channels.ClosedChannelException` means, that there has been once again an issue with the pipeline?

**Comment by clalancette** [comment]
> hm, I guess a `java.nio.channels.ClosedChannelException` means, that there has been once again an issue with the pipeline?

Sigh, yes.  This PR is cursed.  It got automatically rerun, though, and I found that job and updated it.  So this looks good.

**Pull request merged**
