### PR TITLE
This fixes the order of parameters returned 

### PR DESCRIPTION
**Pull request by tfoote**
Connects to ros2/system_tests#10

### CODE REVIEW

**Comment by esteve** [comment]
+1

**Comment by wjwwood** [comment]
Looks ok to me

**Comment by dirk-thomas** [comment]
LGTM (beside the failing style checks)

**Comment by tfoote** [comment]
fixed style to pass uncrustify

My linux ci job failed before getting to my tests. 

http://ci.ros2.org/job/ros2_batch_ci_linux/198/console
```
9:03:46 Linking CXX executable add_two_ints_client 19:03:46 /home/rosbuild/ci_scripts/workspace/install/lib/librmw.so: undefined reference to `strcpy_s' 19:03:46 collect2: error: ld returned 1 exit status
```

**Comment by dirk-thomas** [comment]
The error related to `strcpy_s` was introduced in ros2/rmw#29 but should be fixed now.

**Comment by dirk-thomas** [comment]
You might want to rebase your PR since it reintroduces numerous warnings: http://ci.ros2.org/job/ros2_batch_ci_windows/212/

**Comment by tfoote** [comment]
rebased. CI is failing atm due to a github issue: 

https://raw.githubusercontent.com/ros2/examples/master/ros2.repos
```
Error 503 backend read error

backend read error
Guru Mediation:

Details: cache-lax1426-LAX 1439843997 2104877639

Varnish cache server
```

**Comment by tfoote** [comment]
CI jobs:
http://ci.ros2.org/job/ros2_batch_ci_linux/202/
http://ci.ros2.org/job/ros2_batch_ci_osx/138/
http://ci.ros2.org/job/ros2_batch_ci_windows/215/ 28 test failures, but they appear to be consistently failing.

**Comment by dirk-thomas** [comment]
How is is validated that this patch fixes the test from ros2/system_tests#14? Currently both PRs use different branch names and are therefore not tested together.

**Comment by tfoote** [comment]
I ran it locally to verify it against the system_tests changes.

**Pull request merged**
