### PR TITLE
Removing "virtual", adding "override" keywords in the package

### PR DESCRIPTION
**Pull request by monidzik**
This pull request is about
- removing "virtual" keywords and 
- adding "override" keywords where necessary

### CODE REVIEW

**Comment by clalancette** [comment]
@monidzik Thanks for the contribution.  However, this is a bit much in a single PR.  I'll ask that you please split this up into a few different PRs, with one focus per-PR.  For instance, one PR would just be adding the override keywords, another would just be adding tests, etc.

Also, it looks like this is failing to build because some of the virtual keywords look to be in the wrong places.  That also will need to be fixed.

**Comment by monidzik** [comment]
@clalancette Ok, I'm splitting this PR into couple of smaller ones, so this one will be all about adding overrides and removing virtuals.

**Comment by clalancette** [comment]
> @clalancette Ok, I'm splitting this PR into couple of smaller ones, so this one will be all about adding overrides and removing virtuals.

Thanks, it is appreciated.

**Comment by claireyywang** [comment]
@monidzik friendly ping. You might want to rebase onto master and look into the failed check. Thanks!

**Comment by claireyywang** [comment]
Linux [Build Status](https://ci.ros2.org/job/ci_linux/8717/)
Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/4549/)
OSX [Build Status](https://ci.ros2.org/job/ci_osx/7120/)
Windows [Build Status](https://ci.ros2.org/job/ci_windows/8631/)

**Comment by monidzik** [comment]
@claireyywang what is a status here, can it be merged?

**Comment by claireyywang** [comment]
> @claireyywang what is a status here, can it be merged?

Hi @monidzik, `rclcpp` is a major dependency for a lot of packages. This PR is undergoing further review and testing to ensure nothing breaks once it's merged.

**Comment by Karsten1987** [comment]
@claireyywang you might want to run a complete CI *build* (with *test* args `--packages-select rclcpp`) for this one to check if follow up packages (i.e. `rclcpp_lifecycle`) are effected on this change.
But in general, these changes are compile time only changes - meaning, if the buildfarm is happy, nothing will break during runtime or tests etc.

**Comment by claireyywang** [comment]
@Karsten1987 Thanks for reviewing! I'm running the complete build right now. Though it seems like all windows CI nodes are down. Might have to wait til next week to run windows CI.

**Comment by claireyywang** [comment]
Compete build
Linux [Build Status](https://ci.ros2.org/job/ci_linux/8763/)
Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/4591/)
OSX 
Windows

**Pull request merged**
