### PR TITLE
[foxy backport] Backport all unit tests and bug fixes, feature branch

### PR DESCRIPTION
**Pull request by brawner**
This is the start of PRs to backport unit tests and some associated bug fixes. This PR will be "rebased and merged", so commit history and hashes can be linked.

Edit: This PR will act as the feature branch, and I'll merge other backports for tests into this one. Either rebase and merging if the commits can be taken as is, or squashed if changes are needed to each backport commit. If squashed, I will only be squashing the required changes into the original commit (not squashing multiple backport commits together)

Backported PRs
Bug fix PRs: #1179, #1178, #1211, #1245, #1246, #1251, #1253, #1252, #1270, #1274, #1281, #1291, #1310,
New testing features: #1232
Unit test PRs: #1184, #1181, #1202, #1197, #1198, #1221, #1189, #1222, #1165, #1272, #1308, #1316, #1322, #1321, #1326, #1325

### CODE REVIEW

**Comment by brawner** [comment]
Testing `--packages-select rclcpp`
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12636/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7597/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10342/)
* Windows [Build Status]

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Review by jacobperron — APPROVED** [review]
I just reviewed for ABI compatibility. I didn't thoroughly review the code.

**Comment by brawner** [comment]
Thanks for checking Jacob!

Even though this is green, I'm going to wait until I open a PR with a few fixes in it.

**Review by ahcorde — APPROVED** [review]

**Comment by brawner** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12655/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7618/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10368/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12588/)

**Comment by brawner** [comment]
Standard tests `--packages-up-to rclcpp`
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12686/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7649/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10401/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12630/)

Cyclonedds only
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12687/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7650/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10402/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12631/)

ConnextDds only 
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12688/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7651/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10403/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12632/)

Debug build
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12689/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7652/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10404/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12633/)

**Comment by brawner** [comment]
PR to adjust timeouts with Connext. These tests are also timing out on master, so this PR targets that and I'll add it to this PR when it's merged.
https://github.com/ros2/rclcpp/pull/1400

**Comment by brawner** [comment]
This also now includes the following PRs:

#1165, #1272, #1329, #1270, #1274, #1281, #1291, #1310, #1308, #1316, #1321, 1326, #1325, #1232, #1189, #1245, #1246, #1251, #1253, #1252, #1336, #1330, #1346, #1343, #1350, #1349, #1344, #1342, #1353, #1358, #1359, #1360, #1363, #1347, #1355, #1317, #1364, #1365, #1352, #1366, #1369, #1368, #1296,

**Comment by brawner** [comment]
Merged #1401 into foxy, which hopefully resolves the windows debug issue.

**Comment by brawner** [comment]
I added only the rclcpp bits from #1400 to this PR. The rest will need to backported separately because there were merge conflicts.

**Comment by brawner** [comment]
Standard tests:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12748/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7709/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10461/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12694/)

Connext only:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12749/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7710/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10462/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12695/)

Debug build:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12750/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7711/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10463/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12696/)

**Comment by brawner** [comment]
Standard tests:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12781/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7740/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10494/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12727/)

Connext only:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12782/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7741/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10495/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12728/)

Debug:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12783/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7742/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10496/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12729/)

**Comment by brawner** [comment]
Final CI results look good. The failing test with connext is the SubscriptionTopicStatisticsFixture which is an existing issue on rolling. cppcheck times out on macos debug, which is a periodic failure and would have to be addressed over at ament_lint.

I set DCO to pass because all commits are signed off by their respective authors. Github just had trouble figuring that out...

**Review by jacobperron — APPROVED** [review]

**Pull request merged**
