### PR TITLE
inline helper functions in rclcpp.hpp to avoid multiple definitions

### PR DESCRIPTION
**Pull request by tfoote**
There are a few functions which need inlining from #174 not caught in the refactor.  This adds them to the refactor branch. This extends #172

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Since the `refactor_typesupport` branches pass the build as well as tests on all platforms I hesitate to pull this in before the merge. Especially since none of the code currently seems to require this.

I am also not sure if requesting inline is the right approach. The implementation could also be moved into a cpp file?

**Comment by tfoote** [comment]
Sure you could merge the rest first. This should easily merge/rebase if you want to do that first. Moving the implementation into a cpp file would also work. I just need to be able to use a library for ros2/ros2#153

**Comment by dirk-thomas** [comment]
With the typesupport being refactored the `ros1_bridge` is already building a library on-top of `rclcpp` which seems to work without a problem.

**Comment by tfoote** [comment]
I suspect that the ros1_bridge is not using these symbols. 

Without this patch I get the following linker errors, with it links fine. 
```
Linking CXX executable tf2_echo
libtf2_ros.a(static_transform_broadcaster.cpp.o): In function `operator"" _s(unsigned long long)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:32: multiple definition of `operator"" _s(unsigned long long)'
CMakeFiles/static_transform_publisher.dir/src/static_transform_broadcaster_program.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:32: first defined here
libtf2_ros.a(static_transform_broadcaster.cpp.o): In function `std::string::_M_data(char*)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:36: multiple definition of `operator"" _s(long double)'
CMakeFiles/static_transform_publisher.dir/src/static_transform_broadcaster_program.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:36: first defined here
libtf2_ros.a(static_transform_broadcaster.cpp.o): In function `__cast<long int, std::ratio<1l, 1000l> >':
/usr/include/c++/4.8/chrono:175: multiple definition of `operator"" _ms(unsigned long long)'
CMakeFiles/static_transform_publisher.dir/src/static_transform_broadcaster_program.cpp.o:/usr/include/c++/4.8/chrono:175: first defined here
libtf2_ros.a(static_transform_broadcaster.cpp.o): In function `std::string::_M_data(char*)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:47: multiple definition of `operator"" _ms(long double)'
CMakeFiles/static_transform_publisher.dir/src/static_transform_broadcaster_program.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:47: first defined here
libtf2_ros.a(static_transform_broadcaster.cpp.o): In function `operator"" _ns(unsigned long long)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:54: multiple definition of `operator"" _ns(unsigned long long)'
CMakeFiles/static_transform_publisher.dir/src/static_transform_broadcaster_program.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:54: first defined here
libtf2_ros.a(static_transform_broadcaster.cpp.o): In function `__exchange_and_add_single':
/usr/include/c++/4.8/chrono:149: multiple definition of `operator"" _ns(long double)'
CMakeFiles/static_transform_publisher.dir/src/static_transform_broadcaster_program.cpp.o:/usr/include/c++/4.8/chrono:149: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [static_transform_publisher] Error 1
make[1]: *** [CMakeFiles/static_transform_publisher.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
libtf2_ros.a(buffer.cpp.o): In function `operator"" _s(unsigned long long)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:32: multiple definition of `operator"" _s(unsigned long long)'
CMakeFiles/tf2_echo.dir/src/tf2_echo.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:32: first defined here
libtf2_ros.a(buffer.cpp.o): In function `operator"" _s(long double)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:36: multiple definition of `operator"" _s(long double)'
CMakeFiles/tf2_echo.dir/src/tf2_echo.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:36: first defined here
libtf2_ros.a(buffer.cpp.o): In function `__cast<long int, std::ratio<1l, 1000l> >':
/usr/include/c++/4.8/chrono:175: multiple definition of `operator"" _ms(unsigned long long)'
CMakeFiles/tf2_echo.dir/src/tf2_echo.cpp.o:/usr/include/c++/4.8/chrono:175: first defined here
libtf2_ros.a(buffer.cpp.o): In function `operator"" _ms(long double)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:47: multiple definition of `operator"" _ms(long double)'
CMakeFiles/tf2_echo.dir/src/tf2_echo.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:47: first defined here
libtf2_ros.a(buffer.cpp.o): In function `operator"" _ns(unsigned long long)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:54: multiple definition of `operator"" _ns(unsigned long long)'
CMakeFiles/tf2_echo.dir/src/tf2_echo.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:54: first defined here
libtf2_ros.a(buffer.cpp.o): In function `__cast<long double, std::ratio<1l, 1000000000l> >':
/usr/include/c++/4.8/chrono:149: multiple definition of `operator"" _ns(long double)'
CMakeFiles/tf2_echo.dir/src/tf2_echo.cpp.o:/usr/include/c++/4.8/chrono:149: first defined here
libtf2_ros.a(transform_listener.cpp.o): In function `operator"" _s(unsigned long long)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:32: multiple definition of `operator"" _s(unsigned long long)'
CMakeFiles/tf2_echo.dir/src/tf2_echo.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:32: first defined here
libtf2_ros.a(transform_listener.cpp.o): In function `__gnu_cxx::new_allocator<std::_Sp_counted_deleter<tf2_msgs::msg::TFMessage_<std::allocator<void> >*, std::default_delete<tf2_msgs::msg::TFMessage_<std::allocator<void> > >, std::allocator<void>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:36: multiple definition of `operator"" _s(long double)'
CMakeFiles/tf2_echo.dir/src/tf2_echo.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:36: first defined here
libtf2_ros.a(transform_listener.cpp.o): In function `__cast<long int, std::ratio<1l, 1000l> >':
/usr/include/c++/4.8/chrono:175: multiple definition of `operator"" _ms(unsigned long long)'
CMakeFiles/tf2_echo.dir/src/tf2_echo.cpp.o:/usr/include/c++/4.8/chrono:175: first defined here
libtf2_ros.a(transform_listener.cpp.o): In function `~__shared_count':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:47: multiple definition of `operator"" _ms(long double)'
CMakeFiles/tf2_echo.dir/src/tf2_echo.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:47: first defined here
libtf2_ros.a(transform_listener.cpp.o): In function `operator"" _ns(unsigned long long)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:54: multiple definition of `operator"" _ns(unsigned long long)'
CMakeFiles/tf2_echo.dir/src/tf2_echo.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:54: first defined here
libtf2_ros.a(transform_listener.cpp.o): In function `~__shared_count':
/usr/include/c++/4.8/chrono:149: multiple definition of `operator"" _ns(long double)'
CMakeFiles/tf2_echo.dir/src/tf2_echo.cpp.o:/usr/include/c++/4.8/chrono:149: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [tf2_echo] Error 1
make[1]: *** [CMakeFiles/tf2_echo.dir/all] Error 2
Linking CXX executable tf2_monitor
libtf2_ros.a(buffer.cpp.o): In function `operator"" _s(unsigned long long)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:32: multiple definition of `operator"" _s(unsigned long long)'
CMakeFiles/tf2_monitor.dir/src/tf2_monitor.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:32: first defined here
libtf2_ros.a(buffer.cpp.o): In function `operator"" _s(long double)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:36: multiple definition of `operator"" _s(long double)'
CMakeFiles/tf2_monitor.dir/src/tf2_monitor.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:36: first defined here
libtf2_ros.a(buffer.cpp.o): In function `__cast<long int, std::ratio<1l, 1000l> >':
/usr/include/c++/4.8/chrono:175: multiple definition of `operator"" _ms(unsigned long long)'
CMakeFiles/tf2_monitor.dir/src/tf2_monitor.cpp.o:/usr/include/c++/4.8/chrono:175: first defined here
libtf2_ros.a(buffer.cpp.o): In function `operator"" _ms(long double)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:47: multiple definition of `operator"" _ms(long double)'
CMakeFiles/tf2_monitor.dir/src/tf2_monitor.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:47: first defined here
libtf2_ros.a(buffer.cpp.o): In function `operator"" _ns(unsigned long long)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:54: multiple definition of `operator"" _ns(unsigned long long)'
CMakeFiles/tf2_monitor.dir/src/tf2_monitor.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:54: first defined here
libtf2_ros.a(buffer.cpp.o): In function `__cast<long double, std::ratio<1l, 1000000000l> >':
/usr/include/c++/4.8/chrono:149: multiple definition of `operator"" _ns(long double)'
CMakeFiles/tf2_monitor.dir/src/tf2_monitor.cpp.o:/usr/include/c++/4.8/chrono:149: first defined here
libtf2_ros.a(transform_listener.cpp.o): In function `operator"" _s(unsigned long long)':
/usr/include/c++/4.8/bits/move.h:176: multiple definition of `operator"" _s(unsigned long long)'
CMakeFiles/tf2_monitor.dir/src/tf2_monitor.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:32: first defined here
libtf2_ros.a(transform_listener.cpp.o): In function `operator"" _s(long double)':
/usr/include/c++/4.8/functional:2030: multiple definition of `operator"" _s(long double)'
CMakeFiles/tf2_monitor.dir/src/tf2_monitor.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:36: first defined here
libtf2_ros.a(transform_listener.cpp.o): In function `__cast<long int, std::ratio<1l, 1000l> >':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/node_impl.hpp:162: multiple definition of `operator"" _ms(unsigned long long)'
CMakeFiles/tf2_monitor.dir/src/tf2_monitor.cpp.o:/usr/include/c++/4.8/chrono:175: first defined here
libtf2_ros.a(transform_listener.cpp.o): In function `operator"" _ms(long double)':
/home/tfoote/work/ros2/tf3/install/include/rclcpp/node_impl.hpp:170: multiple definition of `operator"" _ms(long double)'
CMakeFiles/tf2_monitor.dir/src/tf2_monitor.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:47: first defined here
libtf2_ros.a(transform_listener.cpp.o): In function `operator"" _ns(unsigned long long)':
/usr/include/c++/4.8/bits/shared_ptr_base.h:957: multiple definition of `operator"" _ns(unsigned long long)'
CMakeFiles/tf2_monitor.dir/src/tf2_monitor.cpp.o:/home/tfoote/work/ros2/tf3/install/include/rclcpp/rclcpp.hpp:54: first defined here
libtf2_ros.a(transform_listener.cpp.o): In function `__cast<long double, std::ratio<1l, 1000000000l> >':
/usr/include/c++/4.8/bits/shared_ptr_base.h:493: multiple definition of `operator"" _ns(long double)'
CMakeFiles/tf2_monitor.dir/src/tf2_monitor.cpp.o:/usr/include/c++/4.8/chrono:149: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [tf2_monitor] Error 1
make[1]: *** [CMakeFiles/tf2_monitor.dir/all] Error 2
make: *** [all] Error 2
```

I've rebased this against master. 
CI: 
- http://ci.ros2.org/job/ci_linux/716/
- http://ci.ros2.org/job/ci_osx/593/
- http://ci.ros2.org/job/ci_windows_opensplice/782/
- http://ci.ros2.org/job/ci_windows_connext_static/57
- http://ci.ros2.org/job/ci_windows_connext_dynamic/47

**Comment by tfoote** [comment]
Superseded by #178

**Pull request closed without merging**
