### PR TITLE
deprecate the static single threaded executor

### PR DESCRIPTION
**Pull request by alsora**
This PR marks the `StaticSingleThreadedExecutor` as deprecated.
With the current implementation, all other single threaded executors have better performance than this one and they are more stable.

See https://discourse.ros.org/t/the-ros-2-c-executors/38296 for a recent performance comparison that I run.

### CODE REVIEW

**Review by clalancette — COMMENTED** [review]
I'm totally on board with this deprecation, however:

1.  We are almost certainly going to have to make changes to the tests to either remove tests from StaticSingleThreadedExecutor, or suppress this warning (CI should show this).
2.  I'd like to get @wjwwood and/or @mjcarroll to approve.

**Review by mjcarroll — APPROVED** [review]
I approve (and this was always the goal).

**Comment by mjcarroll** [comment]
>  or suppress this warning

We should probably suppress the warning for this iteration before removing entirely next time (to stick with our tick-tock policy)

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI

**Comment by alsora** [comment]
I removed the performance benchmark tests and ignored the deprecation warning for all the unit-tests.
IMO the performance tests are not very useful at this point, but let me know if you prefer to keep those around with the deprecation suppressed.

**Comment by alsora** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21626/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15913/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1129/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22343/)

**Review by clalancette — COMMENTED** [review]
It looks like there are some uncrustify fixes that are needed, but otherwise this looks good to me.

**Comment by alsora** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21637/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15923/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1141/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22354/)

**Comment by clalancette** [comment]
Pulls: ros2/rclcpp#2598
Gist: https://gist.githubusercontent.com/clalancette/6e0606e387dfd155aea36c216fb104f7/raw/72dababdc6724085155820dafffe2865fc3e1c5a/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14387
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21641/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15927/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1145/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22358/)

**Comment by alsora** [comment]
Retrying windows
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22373/)

Does anyone know how to see the warnings produced above?

**Comment by alsora** [comment]
Ok, I can see the windows warnings here https://ci.ros2.org/job/ci_windows/22373/msbuild/#issuesContent.
It looks like it's complaining that I'm using the deprecated class.
I suspect that it's because some tests are using the executor type within a template (e.g. `std::make_shared<ExecutorType>()` ) and this requires the windows compiled to "look inside" the alias, triggering the warning.
I tried a quick fix for that, if it still complains on windows i'll get rid of the alias and use more pragmas to suppress the warnings.

New CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21660/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15944/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1164/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22376/)

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/next-client-library-wg-meeting-friday-16th-august-2024/39130/1

**Comment by clalancette** [comment]
So this generally looks good to me now, but the Rpr job has warnings related to deprecations of the `StaticSingleThreadedExecutor`.  Interestingly, the CI job that @alsora ran does *not* show these warnings.  Any idea what is going on there?

**Comment by alsora** [comment]
@clalancette The warnings in the Rpr job were caused by a new test that was recently introduced.
My rclcpp branch (used in the CI job) didn't include those changes.

I merged with `rolling` to update my branch and fixed those new tests.
Now the Rpr job is happy.

Here a new CI
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21674/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15955/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1175/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22386/)

**Comment by alsora** [comment]
I'm going to merge this since everything is green now!

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/the-ros-2-c-executors/38296/14

**Pull request merged**
