### PR TITLE
Intra-process subscriber should use RMW actual qos. (ros2#913)

### PR DESCRIPTION
**Pull request by malsbat**
Signed-off-by: Todd Malsbary <todd.malsbary@intel.com>

### CODE REVIEW

**Comment by ivanpauno** [comment]
In #913 you refer to a test failing, can you copy a link to the test?
I don't know what test are you talking about.

**Comment by malsbat** [comment]
https://github.com/ros2/system_tests/blob/master/test_rclcpp/test/test_intra_process.cpp is the test that fails.

**Comment by ivanpauno** [comment]
That test isn't failing in any of the nightly ci runs https://ci.ros2.org/view/nightly/.
Can you point out what is different in intel dps rmw implementation? (I understand it's failing with that rmw implementation). It would be good if you can provide the test output.

The changes still look find to me, but I want to make sure I'm not missing something.

**Comment by malsbat** [comment]
The relevant difference here is that the dps rmw does not support all the qos values that e.g. the fastrtps rmw does.  See for example: https://github.com/ros2/rmw_dps/blob/f508310a7a385133bdbceaea11f70a09675a2b53/rmw_dps_cpp/src/rmw_subscription.cpp#L133.

So, in this test the messages fail to get delivered because the requested publisher qos is rewritten to the actual publisher qos supported by dps, while the requested subscriber qos is not, and this causes the can_communicate check to fail.  Once both sides use the actual qos then can_communicate passes and the message is delivered.

The test output when dps fails is the "spin_node_once() - callback (1) expected - try %d/%d\n" repeated until max_loops is reached: the subscription callback is not called.

Let me know if that explains it well enough.  If not I can rebuild before and after this patch and attach the logs.

**Comment by ivanpauno** [comment]
> Let me know if that explains it well enough. If not I can rebuild before and after this patch and attach the logs.

No need, sounds good to me.

> The relevant difference here is that the dps rmw does not support all the qos values that e.g. the fastrtps rmw does. See for example: https://github.com/ros2/rmw_dps/blob/f508310a7a385133bdbceaea11f70a09675a2b53/rmw_dps_cpp/src/rmw_subscription.cpp#L133.

As a side note, I wouldn't recommend to do that in the rmw dps implementation.
Not supported features should fail and log and error, and not be overridden by other setting.
I understand that's more difficult to support, because some tests that are part of the standard ros 2 packages will fail. But just overriding a setting without the user being notified doesn't sound like a good idea to me.

----

CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8659/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4501/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7069/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8579/)

**Comment by malsbat** [comment]
> As a side note, I wouldn't recommend to do that in the rmw dps implementation.
> Not supported features should fail and log and error, and not be overridden by other setting.
> I understand that's more difficult to support, because some tests that are part of the standard ros 2 packages will fail. But just overriding a setting without the user being notified doesn't sound like a good idea to me.
> 
Initially it was implemented as you suggest, but with the introduction of rmw_publisher_get_actual_qos() and rmw_subscriber_get_actual_qos(), I understood that the requested and actual could be different.  Am I misunderstanding the intent of those APIs?

**Comment by ivanpauno** [comment]
> Initially it was implemented as you suggest, but with the introduction of rmw_publisher_get_actual_qos() and rmw_subscriber_get_actual_qos(), I understood that the requested and actual could be different. Am I misunderstanding the intent of those APIs?

It was added to figure out what is the actual qos policy used when `RMW_QOS_POLICY_*_SYSTEM_DEFAULT` was set originally (the system default value is rmw implementation dependent). See https://github.com/ros2/rmw/blob/813b94ddd5650444b312304ad156f3b5d9f05e39/rmw/include/rmw/types.h#L263.

It wasn't thought as a way of setting a different qos policy when one is not available.
If you want to do that, I would recommend to at least log a big warning when that happens.

**Comment by ivanpauno** [comment]
@malsbat can you check the test failures in the above CI jobs? Thanks!

**Comment by malsbat** [comment]
> > Initially it was implemented as you suggest, but with the introduction of rmw_publisher_get_actual_qos() and rmw_subscriber_get_actual_qos(), I understood that the requested and actual could be different. Am I misunderstanding the intent of those APIs?
> 
> It was added to figure out what is the actual qos policy used when `RMW_QOS_POLICY_*_SYSTEM_DEFAULT` was set originally (the system default value is rmw implementation dependent). See https://github.com/ros2/rmw/blob/813b94ddd5650444b312304ad156f3b5d9f05e39/rmw/include/rmw/types.h#L263.
> 
> It wasn't thought as a way of setting a different qos policy when one is not available.
> If you want to do that, I would recommend to at least log a big warning when that happens.

Thanks for the clarification, I'll need to look into this a bit more deeply.

**Comment by malsbat** [comment]
> @malsbat can you check the test failures in the above CI jobs? Thanks!

Yes, I'll take a look.

**Comment by malsbat** [comment]
@ivanpauno, I've looked into the test failure and it appears that the test is incorrect, but I'd like your input.

The test that's failing is asserting that a QoS of KEEP_LAST with depth of 0 is an invalid intra-process subscription QoS.  However, depth 0 is defined as RMW_QOS_POLICY_DEPTH_SYSTEM_DEFAULT in rmw/types.h so appears to me to be a valid QoS.  In fact, the fastrtps rmw checks for and handles RMW_QOS_POLICY_DEPTH_SYSTEM_DEFAULT explicitly when filling in the QoS supplied to the lower layers.

The test previously passed because the intra-process check explicitly looks for depth 0 and throws.  Prior to this change it would see depth 0 (from the requested QoS), but with this change it now sees the system default depth (actual QoS, non-0) and does not throw.

**Comment by ivanpauno** [comment]
> @ivanpauno, I've looked into the test failure and it appears that the test is incorrect, but I'd like your input.
> 
> The test that's failing is asserting that a QoS of KEEP_LAST with depth of 0 is an invalid intra-process subscription QoS. However, depth 0 is defined as RMW_QOS_POLICY_DEPTH_SYSTEM_DEFAULT in rmw/types.h so appears to me to be a valid QoS. In fact, the fastrtps rmw checks for and handles RMW_QOS_POLICY_DEPTH_SYSTEM_DEFAULT explicitly when filling in the QoS supplied to the lower layers.
> 
> The test previously passed because the intra-process check explicitly looks for depth 0 and throws. Prior to this change it would see depth 0 (from the requested QoS), but with this change it now sees the system default depth (actual QoS, non-0) and does not throw.

Sounds good to me, can you update the test?

**Comment by ivanpauno** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/8696/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/4532/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7103/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/8615/)

**Comment by ivanpauno** [comment]
Forgot to check this again, going in! Thanks for the PR @malsbat !

**Pull request merged**
