### PR TITLE
Fix bug on the disorder of calling shutdown callback

### PR DESCRIPTION
**Pull request by Barry-Xu-2018**
Address #2096 

Signed-off-by: Barry Xu <barry.xu@sony.com>

### CODE REVIEW

**Review by alsora — APPROVED** [review]

**Review by fujitatomoya — APPROVED** [review]
lgtm! @Barry-Xu-2018 thanks for quick response.

**Comment by fujitatomoya** [comment]
@clalancette @alsora thanks for the review, btw can we backport this to humble?

**Comment by fujitatomoya** [comment]
I will start the CI.

**Comment by clalancette** [comment]
> @clalancette @alsora thanks for the review, btw can we backport this to humble?

Hm.  So unfortunately, this breaks ABI because of the change of type from `std::unordered_set` to `std::vector`.  So this would not generally be eligible for backporting.  We'd have to consider another non-ABI breaking way to backport this, or explicitly make an exception here.

**Comment by fujitatomoya** [comment]
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18664/)

**Comment by fujitatomoya** [comment]
@clalancette if the backport is hard requirement, we would probably consider other approach. I believe that breaking ABI/API policy would be much bigger problem.

**Comment by Barry-Xu-2018** [comment]
@clalancette @fujitatomoya 

In order to keep ABI compatible, we cannot add new variable (except static variable) into class Context.   
Maybe use global variable as one solution, but it will make code ugly.   
```c++
struct ShutdownCallback {
  std::vector<weak_ptr> pre_callback;
  std::vector<weak_ptr> on_callback;
};

static std:map<Context*, ShutdownCallback> g_shutdownCallback;
static mutex s_shutdownCallback_mutex;
```

Change code on adding/removing/call shutdown callback to use this global variable.   

Now I not find better approach

**Comment by clalancette** [comment]
I'm going to go ahead and merge this one in, since it is an obvious improvement for Rolling.  We can consider fixing Humble (either the documentation or with an ABI-compatible fix) separately.

**Pull request merged**
