### PR TITLE
[rclcpp_components] Enable intra-process comm via LoadNode request.

### PR DESCRIPTION
**Pull request by hidmic**
Look for a 'use_intra_process_comms' boolean in extra_arguments.

### CODE REVIEW

**Comment by hidmic** [comment]
We don't do much testing for `rclcpp_components`, do we? The most relevant one,  `test_component_manager_api` , consistently fails and I bet it has to do repeated node bring up / tear down.

I plan to test this manually, but until https://github.com/ros2/rcl/pull/508 and friends are in `ros2 component` is broken.

**Comment by mjcarroll** [comment]
I believe that it recently went from flaky to more consistently failing, I opened an issue here: https://github.com/ros2/rclcpp/issues/863

**Comment by hidmic** [comment]
Running CI up to `rclcpp_components`:


- Linux [Build Status](https://ci.ros2.org/job/ci_linux/8292/)
- Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/4245/)
- OSX [Build Status](https://ci.ros2.org/job/ci_osx/6762/)
- Windows [Build Status](https://ci.ros2.org/job/ci_windows/8185/)

**Comment by iluetkeb** [comment]
@hidmic Is there an example for how to use this in a launch file?

btw, I'm sure you guys must have plenty of example launch files that the community could have a look at, to figure out how to actually use launch properly. putting them somewhere would be awesome.

**Comment by ZhenshengLee** [comment]
> @hidmic Is there an example for how to use this in a launch file?
> 
> btw, I'm sure you guys must have plenty of example launch files that the community could have a look at, to figure out how to actually use launch properly. putting them somewhere would be awesome.
> 

@iluetkeb 
the `extra_arguments`  is here,  define a `ComposableNode` with this parameter I guess.

https://github.com/ros2/launch_ros/blob/79f783b1fe5e06d71737e2955a8f4eb9c4f3923c/launch_ros/launch_ros/descriptions/composable_node.py#L39-L60

Thanks.

**Pull request merged**
