### PR TITLE
add create_publisher signature which takes just a queue size

### PR DESCRIPTION
**Pull request by wjwwood**
See: https://github.com/ros2/design/issues/56#issue-100899698

Connects to ros2/design#56

### CODE REVIEW

**Comment by dirk-thomas** [comment]
+1

**Comment by wjwwood** [comment]
CI:
- http://ci.ros2.org/job/ros2_batch_ci_linux/435/
- http://ci.ros2.org/job/ros2_batch_ci_osx/345/
- http://ci.ros2.org/job/ros2_batch_ci_windows/487/

**Comment by esteve** [comment]
+1

**Comment by wjwwood** [comment]
This test failed on OS X only, but I cannot reproduce it locally:

http://ci.ros2.org/job/ros2_batch_ci_osx/345/testReport/junit/(root)/test_subscription__rmw_connext_cpp/subscription_shared_ptr_const/

I think it might be a flaky one, especially since this pr shouldn't affect any of the tests.

**Pull request merged**
