### PR TITLE
[foxy backport] Remove rmw-dependent unit-test checks (#1293)

### PR DESCRIPTION
**Pull request by brawner**
* Remove rmw-dependent unit-test checks

Signed-off-by: Stephen Brawner <brawner@gmail.com>

* Address feedback

Signed-off-by: Stephen Brawner <brawner@gmail.com>

* PR Fixup

Signed-off-by: Stephen Brawner <brawner@gmail.com>

### CODE REVIEW

**Comment by brawner** [comment]
Standard foxy build `--packages-select rclcpp_lifecycle`
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12613/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7575/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10321/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12539/)

**Comment by brawner** [comment]
cyclonedds only
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12614/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7576/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10322/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12540/)

**Review by jacobperron — APPROVED** [review]

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Comment by brawner** [comment]
This is all green except for test_lifecycle_service_client on MacOS, which encountered a race condition unrelated to this change (since this PR just affects `test_lifecycle_node.cpp`)

**Pull request merged**
