### PR TITLE
Revert "Revert "Add a create_timer method to Node and `LifecycleNode` classes (#1975)" (#2009)

### PR DESCRIPTION
**Pull request by ivanpauno**
... and fixes the bug introduced in the original PR.

### CODE REVIEW

**Comment by sloretz** [comment]
> We can merge this in replacement of https://github.com/ros2/rclcpp/pull/2009, or after that one is merged (adding here a "revert-revert" commit).

Oops! I just merged the revert.

**Review by sloretz — APPROVED** [review]
LGTM with green CI `--packages-above rclcpp`

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17199/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11742/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17625/)

**Review by fujitatomoya — APPROVED** [review]

**Comment by ivanpauno** [comment]
@Blast545 have you seen those warnings on Windows before?

from the logs:

> 17:54:35 CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.24/Modules/ExternalProject.cmake:3071 (message):
> 17:54:35   The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
> 17:54:35   not set.  The policy's OLD behavior will be used.  When using a URL
> 17:54:35   download, the timestamps of extracted files should preferably be that of
> 17:54:35   the time of extraction, otherwise code that depends on the extracted
> 17:54:35   contents might not be rebuilt if the URL changes.  The OLD behavior
> 17:54:35   preserves the timestamps from the archive instead, but this is usually not
> 17:54:35   what you want.  Update your project to the NEW behavior or specify the
> 17:54:35   DOWNLOAD_EXTRACT_TIM

It seems to be happening in all vendor packages.

**Comment by ivanpauno** [comment]
@ros-pull-request-builder retest this please

**Comment by clalancette** [comment]
> @Blast545 have you seen those warnings on Windows before?

Yes, this is a known issue with the newer version of CMake (3.24).  @Crola1702 is working on it.

**Pull request merged**
