### PR TITLE
Add in two more tests for expand_topic_or_service_name.

### PR DESCRIPTION
**Pull request by clalancette**
This gets us to 100% line coverage.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12538/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7507/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10250/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12459/)

**Review by brawner — APPROVED** [review]
You didn't end up needing the `patch()` variant?

**Comment by clalancette** [comment]
> You didn't end up needing the `patch()` variant?

No, it turns out I was just thinking about it wrong this morning.  Sometimes I just need to walk away and come back to it :).

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
