### PR TITLE
[Dashing backport]: Fix NodeOptions copy constructor (#1376)

### PR DESCRIPTION
**Pull request by ivanpauno**
Backports #1376.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
This backport introduces a PR job failure that's not on the main dashing dev job. Since today is the release cutoff for Patch release 8 I am bumping this to the next patch release.

**Comment by ivanpauno** [comment]
> This backport introduces a PR job failure that's not on the main dashing dev job. Since today is the release cutoff for Patch release 8 I am bumping this to the next patch release.

Seems to be a flake.

@ros-pull-request-builder retest this please

**Comment by ivanpauno** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Review by fujitatomoya — APPROVED** [review]
lgtm, test looks flaky since node graph takes time to update.

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please (test is actually confirming that buildfarm hooks are back online)

**Review by wjwwood — APPROVED** [review]

**Pull request merged**
