### PR TITLE
Fix documentation typos in server_goal_handle.hpp

### PR DESCRIPTION
**Pull request by anacondrai**
Just fixed small typos :)

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by fujitatomoya** [comment]
Pulls: ros2/rclcpp#2668
Gist: https://gist.githubusercontent.com/fujitatomoya/b8bdb907754e4b7bd63ccaa06793335f/raw/3cf725122b00177775e8477f3835b8187a4a6fe9/ros2.repos
BUILD args:  --packages-up-to rclcpp_action
TEST args:  --packages-select rclcpp_action
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14803
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/22109/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16364/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1628/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22851/)

**Comment by fujitatomoya** [comment]
@anacondrai oh sorry, i missed one thing. can you retarget the fix against `rolling` branch? that is the development branch, and the if needed we can backport the fix to the downstream.

**Comment by anacondrai** [comment]
@fujitatomoya Thanks for your comment, I will close this PR to re-target the branch.

**Pull request closed without merging**
