### PR TITLE
Simplify create_service API and encapsulate response dispatching

### PR DESCRIPTION
**Pull request by esteve**
This PR simplifies the `Node::create_service` API and delegates SFINAE to `AnyServiceCallback`.

### CODE REVIEW

**Comment by esteve** [comment]
CI jobs:

http://ci.ros2.org/job/ros2_batch_ci_linux/445/
http://ci.ros2.org/job/ros2_batch_ci_osx/356/
http://ci.ros2.org/job/ros2_batch_ci_windows/498/

**Comment by esteve** [comment]
CI jobs after rebasing:

http://ci.ros2.org/job/ros2_batch_ci_linux/446/
http://ci.ros2.org/job/ros2_batch_ci_osx/357/
http://ci.ros2.org/job/ros2_batch_ci_windows/499/

**Comment by esteve** [comment]
CI jobs:

http://ci.ros2.org/job/ros2_batch_ci_linux/448/
http://ci.ros2.org/job/ros2_batch_ci_osx/360/
http://ci.ros2.org/job/ros2_batch_ci_windows/505/

**Comment by wjwwood** [comment]
Looks reasonable to me. At some point we may want to pass the callback type with an "any" like struct as we do in the subscription function, rather than as separate arguments to ServiceBase, e.g.: https://github.com/ros2/rclcpp/pull/132/files#diff-834b3e16e31ae23dcfb0f5d10d68008eR125

**Comment by esteve** [comment]
@wjwwood I ended up adding the `AnyServiceCallback` class and delegating the logic for dispatching responses to it. I'll do the same to `AnySubscriptionCallback` in a separate branch.

**Comment by wjwwood** [comment]
lgtm

**Comment by esteve** [comment]
CI jobs:

http://ci.ros2.org/job/ros2_batch_ci_linux/451/
http://ci.ros2.org/job/ros2_batch_ci_osx/363/
http://ci.ros2.org/job/ros2_batch_ci_windows/508/

**Comment by esteve** [comment]
I've fixed the style error and squashed the commits.

**Pull request merged**
