### PR TITLE
Avoid reinitializing allocator

### PR DESCRIPTION
**Pull request by jacquelinekay**
Connects to ros2/realtime_support#16

Correct an error message and pass the same allocator to the `AllocSet` (a set of uint64_t) that is stored in a map in IntraProcessManager. This is to avoid reinitializing an allocator on each call to store_intra_process_message. This is useful if the default constructor of an allocator has to preallocate memory, but the copy constructor of an allocator does not.

### CODE REVIEW

**Comment by jacquelinekay** [comment]
I'm also sneaking in the removal of an extraneous sleep in MultiThreadedExecutor pointed out by @tfoote earlier.

**Comment by wjwwood** [comment]
@jacquelinekay does that not overlap with https://github.com/ros2/rclcpp/pull/186?

**Comment by jacquelinekay** [comment]
sorry, I didn't see that!

**Comment by wjwwood** [comment]
It's ok.

tumblr_n2i13gz4ts1r70ozfo4_500

**Comment by jacquelinekay** [comment]
I'll remove the commit that overlaps with #186

**Comment by gerkey** [comment]
+1

**Pull request merged**
