### PR TITLE
[rclcpp] Type Adaptation feature

### PR DESCRIPTION
**Pull request by wjwwood**
This feature, a.k.a. Type Masquerading, is still a WIP.

----

Related:

- https://github.com/ros-infrastructure/rep/pull/303
- ros2/examples#300
- ros2/demos#482
- https://github.com/ros2/demos/pull/497

----

This is part of the Type Masquerading project.

- [ ] Add H-turtle release note (see, https://github.com/ros2/demos/pull/497)

### CODE REVIEW

**Comment by audrow** [comment]
Running tests for `rclcpp` and all packages that depend on it:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14260/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9051/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11943/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14359/)

**Comment by audrow** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14452/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9223/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12124/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14556/)

**Comment by audrow** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14493/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9253/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12162/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14593/)

**Comment by wjwwood** [comment]
CI after finishing updates to the any subscription callback tests:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14507/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9264/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12172/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14606/)

**Comment by wjwwood** [comment]
Re-run of Windows CI to check that the test failure from the last run in `rosbag_cpp` is a flake:

[Build Status](https://ci.ros2.org/job/ci_windows/14631/)

**Review by audrow — APPROVED** [review]
Looks good with green CI.

**Comment by audrow** [comment]
It looks like it may not be building after the last change. Running CI on Linux to double check:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14527/)

**Comment by audrow** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14581/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9336/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12245/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14708/)

**Comment by chriseichmann** [comment]
This also resolves #281, if I understand correctly.

Is there any chance this PR gets backported to Foxy?

**Comment by wjwwood** [comment]
You're right, I closed that issue.

> Is there any chance this PR gets backported to Foxy?

No, I don't think so. The changes were quite extensive and invasive. It would not be possible to make it ABI compatible, in my opinion.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **Open Robotics Discourse**. There might be relevant details there:

https://discourse.openrobotics.org/t/native-rcl-tensor-type/49497/6

**Pull request merged**
