### PR TITLE
Properly test get_service_names_and_types_by_node in rclcpp_lifecycle

### PR DESCRIPTION
**Pull request by christophebedard**
The current `TestLifecycleServiceClient.get_service_names_and_types_by_node` test was using `LifecycleServiceClient`, which is just a normal `rclcpp::Node` with some `rclcpp::Client`s, to test `NodeGraph::get_service_names_and_types_by_node()`. However, `NodeGraph::get_service_names_and_types_by_node()` is for service servers, not clients. The test just ended up checking the built-in services of an `rclcpp::Node`, since it wasn't actually checking the names of the services, and not checking the clients of the `LifecycleServiceClient` or the built-in services of a `rclcpp_lifecycle::LifecycleNode`. I believe this was probably not the intention, since this is an `rclcpp_lifecycle` test.

Instead, use an actual `rclcpp_lifecycle::LifecycleNode` and check its service servers by calling
`NodeGraph::get_service_names_and_types_by_node()` through `LifecycleNode::get_service_names_and_types_by_node()`.

### CODE REVIEW

**Comment by christophebedard** [comment]
I thought that maybe this should instead test `NodeGraph::get_client_names_and_types_by_node()`, but it was added in #1484 after this test was added in #1240, and it's not exposed through `rclcpp::LifecycleNode`. Also, as I mentioned in the PR description, I think this is meant to check the built-in services of an `rclcpp_lifecycle::LifecycleNode`.

**Comment by Barry-Xu-2018** [comment]
A small suggestion. The current test code only checks whether LifecycleNode::get_service_names_and_types_by_node() is called successfully. Should we pick services (such as  /lc_talker/get_state, /lc_talker/change_state) to check if their names exist and their types are correct ?

**Comment by christophebedard** [comment]
good idea, done.

**Review by fujitatomoya — APPROVED** [review]
lgtm with green CI

**Comment by christophebedard** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21643/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15930/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1148/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22361/)

**Pull request merged**
