### PR TITLE
 Fix runtime error: reference binding to null pointer of type

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/rclcpp/issues/1544

### CODE REVIEW

**Comment by fujitatomoya** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13630/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8511/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11344/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13691/)

**Review by clalancette — APPROVED** [review]
This seems reasonable to me, and matches the code we have in `to_rcl_publisher_options`.

**Comment by fujitatomoya** [comment]
i will try to verify this on Ubuntu20.04 host, after that i will merge this one. see https://github.com/ros2/rclcpp/issues/1544#issuecomment-775861094

**Review by wjwwood — APPROVED** [review]

**Comment by fujitatomoya** [comment]
I could not find machine yet :cry: , i will just go ahead to merge this with approvals.

**Pull request merged**
