### PR TITLE
Support publishing loaned messages in LifecyclePublisher

### PR DESCRIPTION
**Pull request by michaelbabenko**
## Problem
Right now LifecyclePublisher doesn't support publishing `LoanedMessage`s. 

## Solution
Override publish for loaned message, implementation is the same as in other overloads, check if publisher is activated and if so, pass message to base publisher

### CODE REVIEW

**Comment by fujitatomoya** [comment]
thanks for opening PR! there is build failure https://build.ros2.org/job/Rpr__rclcpp__ubuntu_jammy_amd64/746/console, can you address it?

**Review by fujitatomoya — COMMENTED** [review]
it would be better to add unit test in `test_lifecycle_publisher.cpp` to make sure if loaned messae can be published with lifecycle states.

**Comment by michaelbabenko** [comment]
Hey, @fujitatomoya, thanks for taking a look at this!

I don't think the build failure is related to my changes, since last merged [PR](https://github.com/ros2/rclcpp/pull/2149) has the same [issue](https://build.ros2.org/job/Rpr__rclcpp__ubuntu_jammy_amd64/710/console).

Added tests.

**Comment by clalancette** [comment]
> I don't think the build failure is related to my changes, since last merged [PR](https://github.com/ros2/rclcpp/pull/2149) has the same [issue](https://build.ros2.org/job/Rpr__rclcpp__ubuntu_jammy_amd64/710/console).

Yeah, right now the Rpr jobs aren't going to work (we expect to have that fixed this week).  We have to rely on the regular CI jobs from https://ci.ros2.org .

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18545/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13090/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19278/)

**Comment by michaelbabenko** [comment]
@fujitatomoya can you help me figure out the CI failure, please?
I only see some java exceptions, which don't look relevant to the PR. I couldn't find any errors related to lifecycle publishers/loaned messages.

**Comment by fujitatomoya** [comment]
something goes wrong during building cyclonedds, https://ci.ros2.org/job/ci_linux/18545/console, could be temporary. I will restart the CI.

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18551/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13095/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19285/)

**Comment by fujitatomoya** [comment]
CI unstable failures are not related to this PR.

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos @Barry-Xu-2018 can i request another review on this?

**Comment by Barry-Xu-2018** [comment]
LGTM

**Review by iuhilnehc-ynos — APPROVED** [review]

**Comment by michaelbabenko** [comment]
@fujitatomoya Assuming I'm good to merge with 3 approves, how do I merge/proceed if there's a build failure?
```
x Rpr__rclcpp__ubuntu_jammy_amd64 — Build finished.
```

**Comment by clalancette** [comment]
> CI unstable failures are not related to this PR.

Hm, but we do not see these failures on the nightlies: https://ci.ros2.org/view/nightly/job/nightly_linux_release/2616/

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Comment by michaelbabenko** [comment]
@clalancette yay, it passes now, thanks!

This PR is ready to be merged, then.
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by clalancette** [comment]
> This PR is ready to be merged, then.

Sorry, I don't think so.  There are failures in the jobs in https://github.com/ros2/rclcpp/pull/2159#issuecomment-1507738545 that we don't see elsewhere.

**Comment by michaelbabenko** [comment]
ah, ok, I though those were unrelated:
>  CI unstable failures are not related to this PR.

I don't see anything related to my changes in the CI logs, is there any way I can replicate the issue locally?

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18557/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13103/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19294/)

**Comment by fujitatomoya** [comment]
@clalancette thanks for restarting CI!

**Pull request merged**
