### PR TITLE
Added support for lambdas

### PR DESCRIPTION
**Pull request by esteve**
This is a quick hack to add support for lambdas.

Connects to #29 

@dirk-thomas @tfoote @wjwwood

### CODE REVIEW

**Comment by esteve** [comment]
@dirk-thomas let me know what you think of this, it's not very readable, but works.

**Comment by dirk-thomas** [comment]
I updated the patch to match style. This works for me with the following userland code:

    auto callback = \
      [](
        const std::shared_ptr<rmw_request_id_t> request_header,
        const std::shared_ptr<userland_msgs::AddTwoInts::Request> request,
        std::shared_ptr<userland_msgs::AddTwoInts::Response> response
      ) -> void
      {
        std::cout << "Got request #" << request_header->sequence_number << std::endl;
        response->sum = request->a + request->b;
      };

    node->create_service<userland_msgs::AddTwoInts>("service_name", callback);

+1

**Comment by wjwwood** [comment]
+1

**Comment by tfoote** [comment]
+1

**Pull request merged**
