### PR TITLE
Fix SharedFuture from async_send_request never becomes valid

### PR DESCRIPTION
**Pull request by llapx**
Signed-off-by: Lei Liu <Lei.Liu.AP@sony.com>

### CODE REVIEW

**Comment by llapx** [comment]
It seems Jenkins broken:

```
17:21:20 FATAL: command execution failed
17:26:12 java.nio.channels.ClosedChannelException
17:26:12 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
17:26:12 	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
17:26:12 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:817)
17:26:12 	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:288)
```
Can anybody fix it?

**Comment by clalancette** [comment]
> It seems Jenkins broken:

With those sorts of errors, Jenkins will automatically re-run it, and it did.  The latest one is failing because test_time_source failed.  That probably bears looking into.

**Comment by iuhilnehc-ynos** [comment]
CI: 

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17633/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12181/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18208/)

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos can you review this? i need another review before merge.

**Review by iuhilnehc-ynos — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@fujitatomoya Should this be backported?

**Comment by fujitatomoya** [comment]
@Mergifyio backport to humble

**Pull request merged**
