### PR TITLE
issue a warning if publishing on a not active publisher

### PR DESCRIPTION
**Pull request by fmrico**
Hi all,

Issue #552 seems to be blocked. @Myzhar did not a PR with his work. This is a PR with his changes.

This PR provides the machanism to issue a WARN when publishing on a not active publisher.

Best

### CODE REVIEW

**Comment by Karsten1987** [comment]
@fmrico thanks for patch. I believe the same comment for PR #552 applies here:
https://github.com/ros2/rclcpp/pull/562#discussion_r222103054

**Comment by fmrico** [comment]
Hi @Karsten1987 ,

I fixed it following the comments in #562 . Is was not so simple, because I had to change logging macros, to make it compile. Macro has changed to:
```
::std::is_same<typename std::remove_reference<decltype(logger)>::type, \
    typename ::rclcpp::Logger>::value, \
    "First argument to logging macros must be an rclcpp::Logger")
```
adding `typename`, because std::remove_reference<Ty>::type is dependant on a template parameter, as I found [here](https://stackoverflow.com/questions/25342985/nesting-standard-type-traits-with-sfinae-fails-to-compile-with-g-4-8).

I run the tests and everything worked ok.

Best

**Comment by Karsten1987** [comment]
Great to hear you made it work. The patch looks good to me so far.
I've triggered the buildfarrm to see if this patch introduces any regression on other tests:

CI:
[Build Status](https://ci.ros2.org/job/ci_linux/5382/)
[Build Status](https://ci.ros2.org/job/ci_linux-aarch64/2100/)
[Build Status](https://ci.ros2.org/job/ci_osx/4464/)
[Build Status](https://ci.ros2.org/job/ci_windows/5334/)

**Comment by Myzhar** [comment]
Great @fmrico 💪

**Pull request merged**
