### PR TITLE
External parameters api

### PR DESCRIPTION
**Pull request by esteve**
Adds the service-based parameter API.

Connects to ros2/ros2#28

Depends on #31 

@dirk-thomas @tfoote @wjwwood please review

### CODE REVIEW

**Comment by esteve** [comment]
Easier to read diff https://github.com/ros2/rclcpp/compare/developer-parameters-api...external-parameters-api

**Comment by dirk-thomas** [comment]
lgtm

**Comment by tfoote** [comment]
+1

**Comment by esteve** [comment]
Thanks for the reviews. I'm working on parameter events, but I'll submit the changes in a followup branch.

**Pull request merged**
