### PR TITLE
Relax template matching rules for std::bind and GNU C++ >= 7.1

### PR DESCRIPTION
**Pull request by esteve**
Connects to #479

### CODE REVIEW

**Comment by esteve** [comment]
@dhood this should fix #479 , but unfortunately I don't have the entire workspace ready right now to build `map_server` or the Turtlebot demo, the test I added in `test_function_traits.cpp` should cover that case.

**Comment by mikaelarguedas** [comment]
Thanks @esteve !

I tested this patch in a tb2 workspace on bionic and it does fix the compilation error :+1:

**Comment by mikaelarguedas** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4499/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1424/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3686/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4576/)

* TB2 demo xenial [Build Status](https://ci.ros2.org/job/ci_turtlebot-demo_linux/126/)

* TB2 demo bionic [Build Status](http://ci.ros2.org/job/ci_bionic_turtlebot-demo_linux/22/)

**Comment by esteve** [comment]
@mikaelarguedas no worries, let me know if there's anything else that needs to be fixed/improved.

@dhood I just noticed that you had submitted #480 to highlight #479. Sorry, I hadn't seen it before submitting this PR. I believe https://github.com/ros2/rclcpp/commit/9d5b0359c75ef3987389ddb105ed64a48b136864#diff-36b58065fa9e8269e336f296c41cdf4cR125 should pass now :crossed_fingers:

**Comment by dhood** [comment]
No worries, thanks for taking a look at it!

**Pull request merged**
