### PR TITLE
Foxy README now points to foxy docs

### PR DESCRIPTION
**Pull request by gstavrinos**
Signed-off-by: George Stavrinos gstavrinos@protonmail.com

### CODE REVIEW

**Comment by clalancette** [comment]
@gstavrinos The commit signature looks malformed (it should be "Signed-off-by: Name <email@place.com>").  Once that is fixed we can merge this.

**Comment by gstavrinos** [comment]
It should be ok now.

**Comment by clalancette** [comment]
The DCO bot is still unhappy, and it still looks like the brackets are missing from the "Signed-off-by" line.

**Comment by gstavrinos** [comment]
Sorry, I missed the brackets.

**Review by clalancette — APPROVED** [review]

**Pull request merged**
