### PR TITLE
add noexcept to get_parameter methods.

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/rclcpp/issues/2047

Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
> and all get_parameter_or

`get_parameter_or` uses template, that could possibly throw `rclcpp::ParameterTypeException`.

**Comment by fujitatomoya** [comment]
@ivanpauno minor fix, could you take a look?

**Comment by ivanpauno** [comment]
Why do we need this?
`noexcept` is a promise that we aren't going to throw exceptions from this method in the future (if not, we will break API).
I'm not sure if we should make that promise.

@wjwwood any opinion?

**Comment by bvolkmer** [comment]
> Why do we need this? `noexcept` is a promise that we aren't going to throw exceptions from this method in the future (if not, we will break API). I'm not sure if we should make that promise.
> 
> @wjwwood any opinion?

But that exactly is the reason to use `noexcept`. If you're going to throw exceptions in the future, it will not silently compile, if someone expects it, not to. As exceptions are most probably a rare occasion (and thus hard to test), it is better to get warnings of a static analyzer after updating an API.

AFAIK, an unfulfilled `noexcept` will throw at most a warning in common compilers.

**Comment by ivanpauno** [comment]
> AFAIK, an unfulfilled noexcept will throw at most a warning in common compilers.

Maybe, I havent' checked if a warning is shown or not. 
It's true that it compiles, and if in the future an exception is thrown I think `std::terminate()` is called.

But I'm not sure if these methods will need to throw an exception in the future or not, so I don't see the point of making a promise now.

e.g. if we add parameter name validation in the future we may need to throw an exception for invalid names in these methods.

**Comment by fujitatomoya** [comment]
> But I'm not sure if these methods will need to throw an exception in the future or not, so I don't see the point of making a promise now.

me neither, i was thinking that with current implementation and code quality, this is worth to add.

**Comment by ivanpauno** [comment]
could you explain what's the benefit of adding that?

**Comment by fujitatomoya** [comment]
it just explicitly declares for user application that this method does(will) not throw exception, and provides safety freedom to the compiler to generator better code for performance(but this could be really small in this case, not really sure).

> if we add parameter name validation in the future we may need to throw an exception for invalid names in these methods.

this is totally correct, adding `noexcept` leads to fragile user interface. if we already have (or may have) such plan, i guess that we can skip adding `noexcept` at this moment.

**Pull request closed without merging**
