### PR TITLE
added wait method to AsyncParametersClient

### PR DESCRIPTION
**Pull request by dirk-thomas**
Rebased version of #337.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/2852/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/356/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2308/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/2991/)

@BrannonKing FYI

**Comment by dirk-thomas** [comment]
I fixed the usage of the visibility macros in 16be382c8c4d1b92dce9c3f8a8cdb73d3132baee

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/2853/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/357/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2309/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/2992/)

**Comment by dirk-thomas** [comment]
The visibility macros set the attributes for dllexport / dllimport depending if the function is being built at compile time of the package or later being used from other code through the header declaration. Since the templated function are header only and are only expanded when actually being used they never end up in the built library of the package containing the declaration and therefore don't need the attributes.

**Comment by dirk-thomas** [comment]
@ros2/team Waiting for review.

**Comment by BrannonKing** [comment]
Thanks.

**Pull request merged**
