### PR TITLE
Don't check lifespan on publisher QoS

### PR DESCRIPTION
**Pull request by rotu**
Similar to changes in https://github.com/ros2/rcl/pull/571
Fixes CI issue http://build.ros2.org/user/rotu/my-views/view/CycloneDDS/job/Fci__nightly-cyclonedds_ubuntu_focal_amd64/31/testReport/rclcpp/TestNode/get_publishers_subscriptions_info_by_topic/
Signed-off-by: Dan Rose <dan@digilabs.io>

### CODE REVIEW

**Comment by rotu** [comment]
@ivanpauno, could you please review this?

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9480/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5208/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7754/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9406/)

**Comment by rotu** [comment]
@ivanpauno What's left to get this merged in?

**Comment by ivanpauno** [comment]
> @ivanpauno What's left to get this merged in?

Nothing, sorry for the delay and thanks for the contribution!

**Pull request merged**
