### PR TITLE
Reflect changes in rclcpp API

### PR DESCRIPTION
**Pull request by prajakta-gokhale**
Fixes CI breakage from https://github.com/ros2/rclcpp/pull/1074

Signed-off-by: Prajakta Gokhale <prajaktg@amazon.com>

### CODE REVIEW

**Comment by prajakta-gokhale** [comment]
Package-only CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10342/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5866/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8424/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10247/)

All upstream packages:

* Linux [Build Status](https://ci.ros2.org/job/ci_linux/10343/)

**Comment by dirk-thomas** [comment]
> Fixes CI breakage from #1074

The build breakage has already been addressed by #1078. If that change isn't necessary anymore please consider reverting it as part of this PR.

**Comment by dirk-thomas** [comment]
At least this linter warning will need to be addressed: https://github.com/ros2/rclcpp/pull/1078#discussion_r412382083

The above CI builds don't show this since you used `--packages-select rclcpp_lifecycle`.

**Comment by wjwwood** [comment]
@prajakta-gokhale you'll need to rebase this on master, at which point I think you'll see that it no longer builds because you need to re-add your changes that were reverted in order to get CI passing again. So this pull request should see all the changes that were originally in https://github.com/ros2/rclcpp/pull/1074 as well as your fixes. Then we need to run a more complete CI over it.

**Comment by dirk-thomas** [comment]
> you need to re-add your changes that were reverted

Nothing got reverted. See #1078 how the build was fixed.

**Comment by prajakta-gokhale** [comment]
Reverted changes made in #1078. CI for `rclcpp` and `rclcpp_lifecycle`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10347/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5870/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8428/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10251/)

**Comment by prajakta-gokhale** [comment]
@wjwwood my commit was not reverted. @dirk-thomas fixed it by providing a default argument in the constructor. This patch fixes the original problem and reverts Dirk's hotfix.

**Comment by wjwwood** [comment]
Oh sorry, I thought it was a revert, my bad.

**Comment by prajakta-gokhale** [comment]
CI for all packages w/ latest commit has no build/test failures. I think this is ready to merge.

**Pull request merged**
