### PR TITLE
Use move semantics to store callback and perfect forwarding to pass it down to GenericTimer

### PR DESCRIPTION
**Pull request by esteve**
Use move semantics to store callback and perfect forwarding to pass it down to GenericTimer

### CODE REVIEW

**Comment by esteve** [comment]
We should probably review our strategy for passing callbacks in the `create_subscription` and `create_service`, and find a uniform policy.

**Comment by esteve** [comment]
CI:

http://ci.ros2.org/job/ci_linux/783/
http://ci.ros2.org/job/ci_osx/650/
http://ci.ros2.org/job/ci_windows/830/

**Comment by esteve** [comment]
Thanks to @jacquelinekay for her help!

**Comment by jacquelinekay** [comment]
+1 for now, can you make an issue for making the callback passing behavior uniform in rclcpp?

**Comment by esteve** [comment]
All tests pass on Linux. The flaky multithreaded and talker/listener examples don't on OSX and Windows, as usual.

**Comment by esteve** [comment]
@jacquelinekay done: https://github.com/ros2/rclcpp/issues/189

**Pull request merged**
