### PR TITLE
Update data callback tests to account for all published samples.

### PR DESCRIPTION
**Pull request by asorbini**
This PR updates some unit tests related to the data callbacks for subscriptions, clients, and services, to make them more robust when run on different RMWs.

The changes were identified while investigating [some failures observed when running the tests with `rmw_connextdds`](https://github.com/ros2/rmw_connextdds/pull/76#issuecomment-1071783755) as part of ros2/rmw_connextdds#76.

In particular, all tests at one point try to publish 3 messages and subsequently expect all 3 samples to be notified via callback.
For this to happen reliably, the endpoints should all be using a History depth of at least 3. Moreover, the tests should wait for the counter variable to be increased up to 3 before making any further assertion.

### CODE REVIEW

**Review by alsora — APPROVED** [review]

**Comment by alsora** [comment]
CI

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16378/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10987/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16750/)

**Comment by clalancette** [comment]
Looks like some uncrustify failures; @asorbini can you take a look?

**Comment by asorbini** [comment]
@clalancette thank you for running CI, the error should be resolved now.

I restarted the jobs for validation:
- Linux: [Build Status](https://ci.ros2.org/job/ci_linux/16389/)
- Linux-aarch64: [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/10998/)
- Windows: [Build Status](https://ci.ros2.org/job/ci_windows/16761/)

**Comment by ivanpauno** [comment]
Repos file is outdated after https://github.com/ros2/ros2/pull/1248/, relaunching the jobs ...

**Comment by ivanpauno** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/16393/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11002/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/16765/)

**Comment by fujitatomoya** [comment]
@ivanpauno 

windows warning https://ci.ros2.org/job/ci_windows/16765/msbuild/new/ is unrelated and that is addressed by https://github.com/ros2/rmw_fastrtps/pull/592.

**Review by fujitatomoya — APPROVED** [review]

**Pull request merged**
