### PR TITLE
Fix benchmark test failure introduced in #1522

### PR DESCRIPTION
**Pull request by ivanpauno**
Fixes https://github.com/ros2/rclcpp/issues/1563#event-4377746517.

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]

**Comment by ivanpauno** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13737/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8607/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11448/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13811/)

**Comment by ivanpauno** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13738/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8608/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11449/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13812/)

**Comment by ivanpauno** [comment]
The "Manually-specified variables were not used by the project: AMENT_RUN_PERFORMANCE_TESTS" cmake warning can be safely ignored.

@cottsay is there a way to run the benchmark tests in CI avoiding that warning? (i.e. to somehow filter it from the report)

**Comment by cottsay** [comment]
> is there a way to run the benchmark tests in CI avoiding that warning

Yes, add the CMake argument `--no-warn-unused-cli`.

**Comment by cottsay** [comment]
There is no way to suppress this message on Windows and aarch64, though. It is expected when you try to run performance tests on those platforms, and can be ignored.
`'osrf_testing_tools_cpp' memory tools are not available, C++ tests using 'performance_test_fixture' can not be run and will be skipped.`

**Comment by ivanpauno** [comment]
Thanks for the info @cottsay !

**Pull request merged**
