### PR TITLE
[dashing backport] Type conversions fixes (#901)

### PR DESCRIPTION
**Pull request by hidmic**
* Fix type conversions

Signed-off-by: Monika Idzik <monika.idzik@apex.ai>

* Add static_casts

Signed-off-by: Monika Idzik <monika.idzik@apex.ai>

* Address PR comments

Signed-off-by: Monika Idzik <monika.idzik@apex.ai>

* Remove one time use variable

Signed-off-by: Monika Idzik <monika.idzik@apex.ai>

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
I'm hopefully fixing a few more CI issues before running CI and approving this change myself. I may combine it with other rclcpp backport PRs into an omnibus for CI.

**Comment by ivanpauno** [comment]
@nuclearsandwich is something else pending, or can CI be run here?

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich is something else pending, or can CI be run here?

Nope CI is running, this just wasn't on the Dashing P7 board so I lost track of it.

**Comment by nuclearsandwich** [comment]
CI up to test_rclcpp running test_rclcpp and rclcpp tests. Since there is linter-drift between CI linter versions and Dashing I generally disable linter tests for full Dashing CI runs but I've left them running here. Any linter issues which are not from the changes in this backport can be disregarded.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11598/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6739/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9483/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11563/)

**Comment by hidmic** [comment]
CI test failures on MacOS and Windows seem completely unrelated. Re-running CI against stable `dashing`: 
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9661/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11770/)

**Comment by ivanpauno** [comment]
@hidmic is this ready to be merged?

**Comment by hidmic** [comment]
Indeed is!

**Pull request merged**
