### PR TITLE
make type support helper supported for service

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
to extend the type support for service
required by https://github.com/ros2/rclcpp/pull/2358

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos just checking, this one is required to https://github.com/ros2/rosbag2/pull/1481? right?

**Comment by iuhilnehc-ynos** [comment]
> @iuhilnehc-ynos just checking, this one is required to [ros2/rosbag2#1481](https://github.com/ros2/rosbag2/pull/1481)? right?

Yes, but not necessary. After checking, I think `rosbag2_cpp` can update its `get_typesupport_handle` to support getting `rosidl_service_type_support_t`. I mean this PR should not block https://github.com/ros2/rosbag2/pull/1481.

**Comment by Barry-Xu-2018** [comment]
@iuhilnehc-ynos @fujitatomoya 

> After checking, I think rosbag2_cpp can update its get_typesupport_handle to support getting rosidl_service_type_support_t. I mean this PR should not block https://github.com/ros2/rosbag2/pull/1481.

Yes. 
But https://github.com/ros2/rosbag2/pull/1481 depended on rclcpp::GenericClient which used updated get_typesupport_handle() (Refer to https://github.com/Barry-Xu-2018/rclcpp/tree/review/topic-generic-client-support).

**Comment by iuhilnehc-ynos** [comment]
Got it.

I think it's better to create a PR for https://github.com/Barry-Xu-2018/rclcpp/tree/review/topic-generic-client-support.
and current PR is required for https://github.com/Barry-Xu-2018/rclcpp/tree/review/topic-generic-client-support.

**Comment by Barry-Xu-2018** [comment]
@iuhilnehc-ynos 

> I think it's better to create a PR for https://github.com/Barry-Xu-2018/rclcpp/tree/review/topic-generic-client-support.

Yes. I created a draft PR #2358. 
After this PR is merged, I will rebase that PR and remove draft label.

**Comment by iuhilnehc-ynos** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19733/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14239/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20460/)

**Comment by iuhilnehc-ynos** [comment]
@fujitatomoya @clalancette @wjwwood 

Could you help me reivew this PR? Suggestions are welcome.

**Review by clalancette — APPROVED** [review]
This looks good to me with green CI (make sure to run `--packages-above-and-dependencies rclcpp`, since this could have downstream effects).

**Comment by fujitatomoya** [comment]
@clalancette thanks and understood.

Full CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19929/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14404/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20636/)

**Comment by clalancette** [comment]
@iuhilnehc-ynos @fujitatomoya Would you mind adding a release note to http://docs.ros.org/en/rolling/Releases/Release-Jazzy-Jalisco.html about this deprecation?  Since it is an implementation detail, I don't think it will affect many users, but it is still good to have a note about it.

**Comment by fujitatomoya** [comment]
@clalancette i can do that. i am gonna get back to you with PR.

**Comment by clalancette** [comment]
> @clalancette i can do that. i am gonna get back to you with PR.

Thank you, it is appreciated.

**Pull request merged**
