### PR TITLE
to support declare parameter with int and float vector

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
Signed-off-by: Chen Lihui <lihui.chen@sony.com>

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
lgtm

**Comment by fujitatomoya** [comment]
@jacobperron could you take a look when you have time?

**Review by jacobperron — APPROVED** [review]
LGTM

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14849/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9599/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12516/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15008/)

**Pull request merged**
