### PR TITLE
add logger level service to lifecycle node.

### PR DESCRIPTION
**Pull request by fujitatomoya**
address https://github.com/ros2/rclcpp/issues/2273

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
@iuhilnehc-ynos i am hesitating to add whole test for `LifecycleNode` because it has the same object `node_logging_` with `Node`. we can add the test under `rclcpp_lifecycle/test` to make sure `LifecycleNode` creates the logging level services as `Node` does. but i do not want to add unnecessary test that could increase the test time. what do you think?

**Comment by iuhilnehc-ynos** [comment]
> i do not want to add unnecessary test that could increase the test time. what do you think?

Yeah, it seems unnecessary for `lifecycle_node` to add the whole test similar to what the `node` did.
I think we can just add a very simple test to check whether the two services(set_logger_levels and get_logger_levels) are enabled (if  node.option(`enable_logger_service`) is true ) or not (if using the default node.option), something like

https://github.com/ros2/rclcpp/blob/a7a9b78feebff603e5c7c5506ce31b89916bde36/rclcpp_lifecycle/test/test_lifecycle_node.cpp#L670-L674

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos requesting final review. i just added the test to check if the service is available or not as you suggested with https://github.com/ros2/rclcpp/pull/2277#issuecomment-1681803846

**Review by iuhilnehc-ynos — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos thanks for the review.

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19396/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13925/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/20117/)

**Comment by fujitatomoya** [comment]
@clalancette I will go ahead to merge this with @iuhilnehc-ynos 's approval.

btw, do we want to backport this to iron? originally this feature is introduced on iron and we can keep the ABI. personally i think it would be nicer for user, since `LifecycleNode` can have the same feature. what do you think?

**Comment by fujitatomoya** [comment]
@Mergifyio backport to iron

**Pull request merged**
