### PR TITLE
Reduce overhead for inheriting from rclcpp::Executor when base functionality is not reused

### PR DESCRIPTION
**Pull request by wjwwood**
refactor of "API Changes for Multihtreaded Events Executor": https://github.com/ros2/rclcpp/pull/2466

### CODE REVIEW

**Comment by wjwwood** [comment]
Tests are passing for me locally on `rclcpp` and `rclcpp_lifecycle`, running CI now:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20872/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15175/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21554/)

**Comment by wjwwood** [comment]
Well, CI passed finally, but Windows too way too long, so we're past the deadline. I'm going to ask for an exception for merging this one in tomorrow's meeting.

**Review by alsora — APPROVED** [review]

**Comment by wjwwood** [comment]
We got approval in the ROS 2 meeting, we'll announce this exception on discourse too. Merging it now. 🎉

**Review by fujitatomoya — COMMENTED** [review]
already merged, lgtm as history.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/freeze-of-ros-2-base-packages-upcoming-branch-and-tutorial-party-for-jazzy-jalisco/37191/2

**Pull request merged**
