### PR TITLE
[foxy backport] Refactor test CMakeLists.txt (#1422) and moving rosidl_generate_interfaces_call (#1424) 

### PR DESCRIPTION
**Pull request by brawner**
I combined these two backports since #1422 introduces a bug and #1424 addresses it. The commit for #1424 had to be adjusted to work in this commit order, since #1424 is later on rolling.

### CODE REVIEW

**Review by cottsay — APPROVED** [review]

**Comment by brawner** [comment]
Building foxy with benchmarks on and testing `--packages-select rclcpp`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12975/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7926/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10696/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12947/)

**Review by ahcorde — CHANGES_REQUESTED** [review]
cppcheck is failing in MAC

**Comment by brawner** [comment]
It looks like cppcheck just timed out, which we have seen periodically. That timeout is controlled in ament_lint/ament_cppcheck. We should see if that's still a common occurence, but for the sake of making sure all these PRs get in today, I'm going to go ahead with this one.

**Comment by brawner** [comment]
Squash merging, since two commits address issues introduced by the first.

**Pull request merged**
