### PR TITLE
Remove deprecated header scope_exit.hpp

### PR DESCRIPTION
**Pull request by emersonknapp**
It was deprecated in H for removal in I

@christophebedard

### CODE REVIEW

**Comment by emersonknapp** [comment]
My pleasure - I really like deleting code :grin:

**Comment by clalancette** [comment]
> My pleasure - I really like deleting code grin

One of my proudest moments was a PR which was like +10, -10000 :).

As far as this PR is concerned, this is fine and we are fairly confident that the core has no uses (otherwise CI would have been yellow).  But we don't know whether that is the case for the larger ecosystem.  So I'm going to request we hold off on merging this one until we open a release note for it.  I'm happy to do that, but I first want to get https://github.com/ros2/ros2_documentation/pull/3395 landed.

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI and assuming https://github.com/ros2/ros2_documentation/pull/3402 gets merged at the same time.

**Comment by emersonknapp** [comment]
Gist: https://gist.githubusercontent.com/emersonknapp/37a24cfacf9a38830166bd1dee724f5d/raw/dca003635973b67f2a0738ab71af708e3ef993f6/ros2.repos
BUILD args:  --packages-above-and-dependencies rclcpp
TEST args:  --packages-above rclcpp
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/11668
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18307/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12831/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18975/)

**Pull request merged**
