### PR TITLE
[foxy] Fix occasionally missing goal result caused by race condition (#1677)

### PR DESCRIPTION
**Pull request by fujitatomoya**
* Fix occasionally missing goal result caused by race condition

Signed-off-by: Kaven Yau <kavenyau@foxmail.com>

* Take action_server_reentrant_mutex_ out of the sending result loop

Signed-off-by: Kaven Yau <kavenyau@foxmail.com>

* add note for explaining the current locking order in server.cpp

Signed-off-by: Kaven Yau <kavenyau@foxmail.com>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
CC: @ivanpauno @KavenYau

**Review by ivanpauno — APPROVED** [review]

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14680/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9432/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12345/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14823/)

**Comment by fujitatomoya** [comment]
@jacobperron could you review this just in case?

**Review by jacobperron — APPROVED** [review]

**Comment by jacobperron** [comment]
This backports #1677 to Foxy (I like to explicitly reference the original ticket in the backport PR for posterity).

**Pull request merged**
