### PR TITLE
Increase timeouts for connext for long tests

### PR DESCRIPTION
**Pull request by brawner**
Destroying nodes takes upwards of 3 seconds, which can cause many unit tests to take inordinate amount of time (#1250) with rmw_connext_cpp. Currently only `test_executors` and `test_allocator_memory_strategy` timeout, so the timeout is being increased here.

Signed-off-by: Stephen Brawner <brawner@gmail.com>

### CODE REVIEW

**Comment by brawner** [comment]
Testing connext only (`--packages-select rclcpp`)
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11739/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9577/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11679/)

**Comment by dirk-thomas** [comment]
If the test commonly exits fast I would suggest applying the longer timeout generically without rmw specific logic.

**Comment by brawner** [comment]
Updated the code so that the timeouts aren't specific to connext. Also, `test_allocator_memory_strategy` needed a further boost in time to finish. That test does not pass itself though for connext and those fixes are resolved in #1252

**Comment by brawner** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11750/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9586/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11685/)

**Comment by brawner** [comment]
Tests look like they all finished within their timeouts. `test_allocator_memory_strategy` takes nearly 4 minutes with connext because it includes so many unit tests (#1250). With FastRTPS it takes 200ms.

https://ci.ros2.org/view/nightly/job/nightly_linux_release/1628/testReport/rclcpp/TestAllocatorMemoryStrategy/

**Pull request merged**
