### PR TITLE
fix memory leak

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
to fix https://github.com/ros2/rclcpp/issues/1993

Signed-off-by: Chen Lihui <lihui.chen@sony.com>

### CODE REVIEW

**Review by alsora — APPROVED** [review]
Looks good to me!
Thanks for fixing the leak!

**Review by clalancette — APPROVED** [review]
Good fix.  Looks good with green CI.

**Comment by iuhilnehc-ynos** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17145/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11692/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17569/)

**Comment by iuhilnehc-ynos** [comment]
Update build parameter from `--packages-select rclcpp` to `--packages-up-to rclcpp`.
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17146/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11693/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17570/)

**Review by fujitatomoya — APPROVED** [review]

**Pull request merged**
