### PR TITLE
Revert "Revert "extract the result response before the callback is is…

### PR DESCRIPTION
**Pull request by fujitatomoya**
…sued. (#2133)" (#2148)"

This reverts commit 19a666f1c9393e86f0f0cc5a8213cbd18b01fc03.

### CODE REVIEW

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18378/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12916/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19049/)

**Comment by fujitatomoya** [comment]
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12918/)

**Review by iuhilnehc-ynos — APPROVED** [review]

**Comment by fujitatomoya** [comment]
https://ci.ros2.org/job/ci_linux-aarch64/12918/console hmmm, i am not sure why this is failing to complete, tests look good.

**Comment by fujitatomoya** [comment]
@Mergifyio backport foxy

**Pull request merged**
