### PR TITLE
inline helper functions in rclcpp.hpp to avoid multiple definitions

### PR DESCRIPTION
**Pull request by tfoote**
Retargeting #176 against master
CI:

http://ci.ros2.org/job/ci_linux/716/
http://ci.ros2.org/job/ci_osx/593/
http://ci.ros2.org/job/ci_windows_opensplice/782/
http://ci.ros2.org/job/ci_windows_connext_static/57
http://ci.ros2.org/job/ci_windows_connext_dynamic/47

### CODE REVIEW

**Comment by dirk-thomas** [comment]
My previous comment still applies: why making the functions inline instead of moving the implementation to a .cpp file?

**Comment by tfoote** [comment]
This is the simplest solution to fix the problem of over linking which is blocking my other progress.

**Comment by jacquelinekay** [comment]
It's a bit tricky because these functions aren't namespaced. I started a branch called helper_functions_cpp that follows Dirk's suggestion and I'm trying to build it on Windows right now. Will let you know how it goes:

https://github.com/ros2/rclcpp/compare/helper_functions_cpp

**Comment by gerkey** [comment]
@tfoote Double-check why the return values are const. Otherwise, +1

**Comment by wjwwood** [comment]
I'm not sure if they need to be const, but they are returning a literal converted into different type, so it's really a different view of a literal, which should always be const. In the C++14 implementation of the time literals they actually use `constexpr`:

http://en.cppreference.com/w/cpp/chrono/operator%22%22s

I believe I was doing that until I realized it didn't work right on Windows, but it might now.

**Comment by tfoote** [comment]
Thanks for explaining the reason for const @wjwwood This is something we should plan to replace once c++14 is available with the full implementation so I'll leave it as const for now.

**Pull request merged**
