### PR TITLE
Replace usage of typedef with using

### PR DESCRIPTION
**Pull request by esteve**
Depends on #87 

Connects to ros2/ros2#85

### CODE REVIEW

**Comment by esteve** [comment]
CI jobs:

http://ci.ros2.org/job/ros2_batch_ci_windows/181/
http://ci.ros2.org/job/ros2_batch_ci_linux/191/
http://ci.ros2.org/job/ros2_batch_ci_osx/127/

**Comment by dirk-thomas** [comment]
I stopped the Windows job for now. I will reschedule it later.

**Comment by esteve** [comment]
New CI jobs:

http://ci.ros2.org/job/ros2_batch_ci_windows/191/
http://ci.ros2.org/job/ros2_batch_ci_linux/193/
http://ci.ros2.org/job/ros2_batch_ci_osx/128/

**Comment by jacquelinekay** [comment]
+1

**Comment by tfoote** [comment]
+1

**Pull request merged**
