### PR TITLE
[Backport foxy] rclcpp_lifecycle: Increased coverage

### PR DESCRIPTION
**Pull request by ahcorde**

### CODE REVIEW

**Review by brawner — APPROVED** [review]

**Comment by ahcorde** [comment]
Compiling up-to `rclcpp_lifecycle` and testing `rclcpp_lifecycle`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12856/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7811/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10567/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12799/)

**Comment by ahcorde** [comment]
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10580/)

**Comment by chapulina** [comment]
Is this good to go? :grin:

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12953/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7901/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10670/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12901/)

**Pull request merged**
