### PR TITLE
Pass callbacks as universal references

### PR DESCRIPTION
**Pull request by esteve**
This PR uses universal references for callbacks.

### CODE REVIEW

**Comment by esteve** [comment]
CI:

http://ci.ros2.org/job/ros2_batch_ci_linux/556/
http://ci.ros2.org/job/ros2_batch_ci_osx/427/
http://ci.ros2.org/job/ros2_batch_ci_windows/573/

**Comment by wjwwood** [comment]
Again, I appreciate it if this could be deferred until https://github.com/ros2/rclcpp/pull/140 is merged.

**Comment by esteve** [comment]
Sure, no problem, it's not marked for review yet, though.

**Comment by esteve** [comment]
I've cancelled the CI jobs.

**Comment by esteve** [comment]
CI:

http://ci.ros2.org/job/ros2_batch_ci_linux/568/
http://ci.ros2.org/job/ros2_batch_ci_osx/442/
http://ci.ros2.org/job/ros2_batch_ci_windows/589/

**Comment by dirk-thomas** [comment]
The Windows build will fail since you can only build with a single rmw impl. enabled.

**Comment by esteve** [comment]
I triggered two more jobs, one for OpenSplice and another for Connext:

http://ci.ros2.org/job/ros2_batch_ci_windows/590/
http://ci.ros2.org/job/ros2_batch_ci_windows/591/

**Comment by dirk-thomas** [comment]
The "Connext" job will fail too since you must select a single rmw implementation.

**Comment by esteve** [comment]
http://ci.ros2.org/job/ros2_batch_ci_windows/591/ for Connext static
http://ci.ros2.org/job/ros2_batch_ci_windows/592/ for Connext dynamic

**Comment by jacquelinekay** [comment]
Can you give a summary of why a universal reference is needed, instead of the current behavior, or instead of an lvalue reference?

**Comment by esteve** [comment]
This way we avoid extra copies and passing normal references breaks lambdas.

**Comment by jacquelinekay** [comment]
so you can't pass a lambda to a function by lvalue reference? I couldn't find any documentation on the matter.

I recall you made this PR because of that problem: https://github.com/ros2/rclcpp/pull/143

was it because somewhere the lambdas were being passed as temporaries? Then I can see why perfect forwarding would be needed.

Anyway, regardless of the details, the change is a good idea; I'm trying to learn more about C++11...

**Comment by esteve** [comment]
Yes, the result of a lambda expression is a temporary, which can't be bound to lvalue references, hence the need for universal ones.

**Comment by esteve** [comment]
In general, any function that takes a template argument should use a universal references, unless we really need copies.

**Comment by jacquelinekay** [comment]
+1

**Pull request merged**
